### ISSUE TITLE
Crash during sync in the trie cleaning

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#108]
#### Backtrace

````
INFO [10-04|12:27:59.317] Memory                                   nodes=4999974 alloc=14091714 sys=25457625 numGC=287
INFO [10-04|12:27:59.317] Database                                 size=142020145152 written=570843137
INFO [10-04|12:27:59.358] Imported new chain segment               blocks=31  txs=3409  mgas=173.164  elapsed=11.556s   mgasps=14.984  number=5104347 hash=c38607…61a26
7 batch=584    age=1y7mo3w
INFO [10-04|12:28:07.370] Imported new chain segment               blocks=130 txs=14839 mgas=804.555  elapsed=8.011s    mgasps=100.422 number=5104477 hash=224281…77f2a
1 batch=84155  age=1y7mo3w
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8c090e]
goroutine 53760 [running]:
github.com/ledgerwatch/turbo-geth/trie.(*hasher).hashInternal(0xc2dbe44000, 0x0, 0x0, 0xc0f6d65e00, 0xc07a77fd60, 0x20, 0x20, 0x0, 0x45e491)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/hasher.go:80 +0x8e
github.com/ledgerwatch/turbo-geth/trie.(*hasher).hash(...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/hasher.go:69
github.com/ledgerwatch/turbo-geth/trie.(*Trie).unload(0xc000ec5480, 0xc28b06e400, 0x40, 0x40, 0xc2dbe44000)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:1255 +0x4bd
github.com/ledgerwatch/turbo-geth/trie.pruneMap(0xc000ec5480, 0xc227afef70, 0xc2dbe44000, 0x41)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:160 +0x232
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).PruneToTimestamp(0xc000554c60, 0xc000ec5480, 0x4d1fcc)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:189 +0x266
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).PruneTo(0xc000554c60, 0xc000ec5480, 0x4c4b40, 0x1)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:216 +0xbf
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).PruneTries(0xc0000e2a10, 0x216e7000)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:1043 +0x80
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).insertChain(0xc000170400, 0x1303da0, 0xc187943740, 0xc540418000, 0xb79, 0xb79, 0x1, 0x0, 0x0, 0x0, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/core/blockchain.go:1360 +0x25c0
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).InsertChain(0xc000170400, 0xc540418000, 0xb79, 0xb79, 0x2065648, 0x0, 0x0)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/core/blockchain.go:1068 +0xe04
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).importBlockResults(0xc00025a6e0, 0xc53ff4e000, 0xb79, 0xb79, 0xb79, 0x0)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1471 +0x538
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).processFullSyncContent(0xc00025a6e0, 0xc0001086c0, 0xc0ecee5798)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1445 +0x79
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync.func1(0xc00025a6e0, 0xc244e00d20, 0xc43c514a10)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:478 +0x59
created by github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:478 +0xaf
(END)
````

**Comment by b00ris** [comment]
```INFO [10-14|19:15:03.019] Imported new chain segment               blocks=439  txs=1056  mgas=1654.054 elapsed=11.954s   mgasps=138.362  number=888308 hash=f2746b…e8ab51 batch=16     age=2y5mo2w
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x44b281e]

goroutine 828 [running]:
github.com/ledgerwatch/turbo-geth/trie.(*hasher).hashInternal(0xc000598000, 0x0, 0x0, 0xc0fb81fc00, 0xc100e5aea0, 0x20, 0x20, 0x0, 0x404ae31)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/trie/hasher.go:80 +0x8e
github.com/ledgerwatch/turbo-geth/trie.(*hasher).hash(...)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/trie/hasher.go:69
github.com/ledgerwatch/turbo-geth/trie.(*Trie).unload(0xc0007ff520, 0xc06a6c2140, 0x40, 0x40, 0xc000598000)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:1255 +0x4bd
github.com/ledgerwatch/turbo-geth/trie.pruneMap(0xc0007ff520, 0xc0d03b2f70, 0xc000598000, 0x42)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:160 +0x232
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).PruneToTimestamp(0xc0008994a0, 0xc0007ff520, 0x92384)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:189 +0x266
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).PruneTo(0xc0008994a0, 0xc0007ff520, 0x100000, 0x1)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:216 +0xbf
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).PruneTries(0xc0002542a0, 0x14d90000)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:1040 +0x80
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).insertChain(0xc00018b000, 0x4f3a9e0, 0xc03a973770, 0xc019d16000, 0x2000, 0x2000, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/core/blockchain.go:1382 +0x25c0
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).InsertChain(0xc00018b000, 0xc019d16000, 0x2000, 0x2000, 0x5a93230, 0x0, 0x0)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/core/blockchain.go:1090 +0xe04
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).importBlockResults(0xc0002086e0, 0xc019b86000, 0x2000, 0x2000, 0x2000, 0x0)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1471 +0x538
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).processFullSyncContent(0xc0002086e0, 0x4f1a740, 0xc000056798)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1445 +0x79
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync.func1(0xc0002086e0, 0xc0009e02a0, 0xc000140130)
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:478 +0x59
created by github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync
        /Users/boris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:478 +0xaf
```

**Comment by AlexeyAkhunov** [comment]
With a bit more diagnostics
```
INFO [10-15|10:25:49.588] Imported new chain segment               blocks=306  txs=439   mgas=1108.633 elapsed=10.217s   mgasps=108.507 number=888386 hash=0f0cef…71166a batch=447    age=2y5mo2w
INFO [10-15|10:25:58.123] Memory                                   nodes=1047500 alloc=4296647 sys=7115180 numGC=711
INFO [10-15|10:25:58.123] Database                                 size=7033360384 written=368263169
INFO [10-15|10:25:58.127] Imported new chain segment               blocks=288  txs=411   mgas=1098.381 elapsed=8.539s    mgasps=128.625 number=888674 hash=084831…7bf6e0 batch=24     age=2y5mo2w
nd == nil, hex 01080b0208090903060a000807040c0c0c0e0e06050701020c08080c0d0a0a000a0300050b0000040d030f0d0a020904020b020b020d0c05040f01040f060101, parent node: *trie.accountNode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x44d095e]

goroutine 50585 [running]:
github.com/ledgerwatch/turbo-geth/trie.(*hasher).hashInternal(0xc064d94000, 0x0, 0x0, 0x0, 0xc0fb1be9e0, 0x20, 0x20, 0x0, 0x0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/hasher.go:80 +0x8e
github.com/ledgerwatch/turbo-geth/trie.(*hasher).hash(...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/hasher.go:69
github.com/ledgerwatch/turbo-geth/trie.(*Trie).unload(0xc000afa4c0, 0xc04ee3e8c0, 0x40, 0x40, 0xc064d94000)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:1148 +0x4c8
github.com/ledgerwatch/turbo-geth/trie.pruneMap(0xc000afa4c0, 0xc17530afa8, 0xc064d94000, 0x44)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:149 +0x216
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).PruneToTimestamp(0xc0001bd590, 0xc000afa4c0, 0x92574)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:176 +0x260
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).PruneTo(0xc0001bd590, 0xc000afa4c0, 0x100000, 0x0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie_pruning.go:201 +0xbf
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).PruneTries(0xc000510000, 0x16003000)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:1068 +0x80
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).insertChain(0xc0000a9c00, 0x4f48f60, 0xc075558b10, 0xc0c9aac000, 0x2000, 0x2000, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/core/blockchain.go:1382 +0x254f
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).InsertChain(0xc0000a9c00, 0xc0c9aac000, 0x2000, 0x2000, 0x5a12f70, 0x0, 0x0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/core/blockchain.go:1090 +0xd87
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).importBlockResults(0xc000208420, 0xc0c98ca000, 0x2000, 0x2000, 0x2000, 0x0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1471 +0x534
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).processFullSyncContent(0xc000208420, 0x14056af8274c47a0, 0x74aa9d68c845e9a0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1445 +0x79
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync.func1(0xc000208420, 0xc1049179e0, 0xc1048e2100)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:478 +0x63
created by github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:478 +0xaf

```
