### ISSUE TITLE
Intermittent error when eth_getBalance is called repeatedly

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1101]
Latest master branch

#### Steps to reproduce:

This is not easy to reproduce. It happens when running many tests right after each other but not from the command line. A `curl` command similar to this one is being called repeatedly during TrueBlocks' tests: 

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","0x1"],"id":64}' -H "Content-Type: application/json" localhost:8545
```

But when I call that curl command from the command line, it succeeds.

#### Comments:

TrueBlocks calls `eth_getBalance` around 1,000 times during its tests. Sometimes (10 out of 1,000?), `eth_getBalance` reports an ERROR in the log (copied below). The log points to [this line](https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/get_balance.go#L24) which dereferences the return from `acc.Balance.ToBig()` without first checking for error. Clearly, there needs to be a test for error at that line, but not sure why it works sometimes and not others.

The tests run very quickly one right after the other, so maybe that's related.

`eth_getBalance` is the only RPC command that shows this type of error.

```
DEBUG[09-10|23:04:06.026] Served                                   conn=127.0.0.1:63323 t=1.322612ms   method=eth_getBalance                          reqid=1 params="[\"0xa1e4380a3b1f749673e270229993ee55f35663b4\",\"0x1\"]"
ERROR[09-10|23:04:06.027] RPC method eth_getBalance crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 111993 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc000517260, 0xe, 0xc000197d58)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xb5
panic(0x4bb0520, 0x56c7910)
	runtime/panic.go:967 +0x166
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GetBalance(0xc00007e960, 0x4ed1b80, 0xc0002a7040, 0xc3b2382cf5af7df2, 0xdf2d6592932bad73, 0xc5033343, 0xc0005172b8, 0x0, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/get_balance.go:24 +0x1e8
reflect.Value.call(0xc00021a600, 0xc0000a25c8, 0x13, 0x4d0342c, 0x4, 0xc00061a120, 0x4, 0x4, 0xc000061bf0, 0x404ee3c, ...)
	reflect/value.go:460 +0x8ab
reflect.Value.Call(0xc00021a600, 0xc0000a25c8, 0x13, 0xc00061a120, 0x4, 0x4, 0x2, 0x2, 0x0)
	reflect/value.go:321 +0xb4
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000098900, 0x4ed1b80, 0xc0002a7040, 0xc000517260, 0xe, 0xc000359e90, 0x2, 0x2, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2b7
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc000137050, 0x4ed1b80, 0xc0002a7040, 0xc000338540, 0xc000098900, 0xc000359e90, 0x2, 0x2, 0x2)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:388 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc000137050, 0xc000359e30, 0xc000338540, 0x203000)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:336 +0x298
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc000137050, 0xc000359e30, 0xc000338540, 0x4ebdf01)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:298 +0x1bd
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc000359e30)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc000137050, 0xc000365660)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:226 +0xcd
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:222 +0x66
WARN [09-10|23:04:06.027] Served                                   conn=127.0.0.1:63323 method=eth_getBalance                          reqid=1 t=1.269375ms   err="method handler crashed"
```

**Comment by AlexeyAkhunov** [comment]
Ok, I think I know how to fix it. We just need to remove some code :)

**Comment by AlexeyAkhunov** [comment]
This may help: https://github.com/ledgerwatch/turbo-geth/pull/1105

**Comment by tjayrush** [comment]
I'm no longer seeing this issue in my testing. Perhaps something changed recently? Can this be closed?
