### ISSUE TITLE
branch logs_index2 - different results of eth_getLogs sometimes, sometimes crashes

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1143]
The same query returns different results in 2 successive runs:

````
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x1e8480", "toBlock": "0x1e84e4", "address": "0xec9f6c9634165f91e22e58b90e3ede393d959e47"}],"id":64}' -H "Content-Type: application/json" 192.168.1.238:8545
````
First response
````
{"jsonrpc":"2.0","id":64,"result":[{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x0000000000000000000000000000000000000000000000000000000000000269","0x000000000000000000000000caac46d9bd68bffb533320545a90cd92c6e98e58"],"data":"0x","blockNumber":"0x1e8484","transactionHash":"0x9fb710702f0b4d002085994cbb08667bda0f63308174f2cb76f15d93c54a9f67","transactionIndex":"0x2","blockHash":"0x7250d1dc6c4b7c1a51f13fb02a92cc60ab1b9592e457ad60813356c656593cc2","logIndex":"0x0","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x00000000000000000000000045d01cc478a3dcfd66607726dc50780f3eb4d7bc","0x0000000000000000000000000000000000000000000000000000002e90edd000"],"data":"0x","blockNumber":"0x1e8486","transactionHash":"0x0bf38cfac67554713083e8ad28b8b64c737a633af2f27b4b68b6033bf504929d","transactionIndex":"0x1","blockHash":"0xb2a862fb022e642626f152cd087ae1a895db9486051f22ece96e6b580f86e000","logIndex":"0x2","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026a","0x000000000000000000000000764b38935b4f1644e0ececae3308a314206edc75"],"data":"0x","blockNumber":"0x1e8493","transactionHash":"0xb7b856480e7112fc0e4e3d75870344fa17d42783e455a50255a978c8a7d44585","transactionIndex":"0x2","blockHash":"0xe417b01ee2ab21ede7f5ce2e15e6c65d7a61c22e5e87b5ac3024503e0764c2a1","logIndex":"0x0","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026b","0x000000000000000000000000580f3d001f78e76eee4ffe9284f7fa14c257ee59"],"data":"0x","blockNumber":"0x1e8493","transactionHash":"0x73dc8f424350d1371dce29a641b49bb49701b6984121594bbda11c4fbf0fb5d6","transactionIndex":"0x4","blockHash":"0xe417b01ee2ab21ede7f5ce2e15e6c65d7a61c22e5e87b5ac3024503e0764c2a1","logIndex":"0x1","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x000000000000000000000000caac46d9bd68bffb533320545a90cd92c6e98e58","0x00000000000000000000000000000000000000000000000000000034630b8a00"],"data":"0x","blockNumber":"0x1e8497","transactionHash":"0x627da1b5b7f911001b2a3bdc6df97a15298294a3e6f787c3ffa78b0225a046d2","transactionIndex":"0x1d","blockHash":"0xedb177b5137ecf5f7029c00b121de5f2ecfc94f0fa39687a029e118a9e652215","logIndex":"0x12","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x000000000000000000000000310d923ddbbee9ffa4d46addd6852d6d3b25c581","0x000000000000000000000000000000000000000000000000000000174876e800"],"data":"0x","blockNumber":"0x1e8498","transactionHash":"0x37aa1f411c2ef6926ea6b86d2b77a73604dcf001569afec20a9923ef6ceb2e51","transactionIndex":"0x3","blockHash":"0xaf32654f1abee523fb8881bc168d72cc7d9599c363dd9048735c7920541f61ec","logIndex":"0x2","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026c","0x000000000000000000000000140e7fac8258de95315830b979eaa1684404111b"],"data":"0x","blockNumber":"0x1e84a7","transactionHash":"0xecd29419a5cc2d96663ae9fe91fe8ce9f5d65dc0978f3ea5f0ea0caee115b04d","transactionIndex":"0x6","blockHash":"0xea7c7ad769c3424cb5965fe0e548e2b89d61a62d0a917dce0831cbc16d2f1a17","logIndex":"0x3","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026d","0x0000000000000000000000007c54ca6d016a7b737480c5429bdd3fa6749ea692"],"data":"0x","blockNumber":"0x1e84aa","transactionHash":"0x18c22789e6e4aea42a39079740f0c0916a0aac17d2a3c3f8fd8c8aa3e6c1acd1","transactionIndex":"0x3","blockHash":"0xfbb97c3adcd88731315324e42e65bc1c0bdd898e3a18a1f3a8d4a1f37a494f6d","logIndex":"0x1","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x0000000000000000000000001ce4596974e4623f59200694c7f00c7fa6ea1e59","0x0000000000000000000000000000000000000000000000000000002e90edd000"],"data":"0x","blockNumber":"0x1e84ac","transactionHash":"0x615c7086ae80d149435b6916ec5570d5246af6378c0852ea4d9b79f397290b1a","transactionIndex":"0x0","blockHash":"0xd7330c838271b34d0e6b97cc90a1aa07c96193c6de1ca4891c15373cc61f9143","logIndex":"0x1","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x000000000000000000000000580f3d001f78e76eee4ffe9284f7fa14c257ee59","0x0000000000000000000000000000000000000000000000000000002f43be2e00"],"data":"0x","blockNumber":"0x1e84b2","transactionHash":"0x0cbe073779461d9fbf406db379adccb44b8231cce866504d94525be7d30de0d2","transactionIndex":"0x2","blockHash":"0xeddad8e6e4ebb1eff5df989704b0d1a26d20207bc58ff898b8214a148713e55b","logIndex":"0x1","removed":false}]}
````
Same request again:
````
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x1e8480", "toBlock": "0x1e84e4", "address": "0xec9f6c9634165f91e22e58b90e3ede393d959e47"}],"id":64}' -H "Content-Type: application/json" 192.168.1.238:8545
````
Different response:
````
{"jsonrpc":"2.0","id":64,"result":[{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x0000000000000000000000000000000000000000000000000000000000000269","0x000000000000000000000000caac46d9bd68bffb533320545a90cd92c6e98e58"],"data":"0x","blockNumber":"0x1e8484","transactionHash":"0x9fb710702f0b4d002085994cbb08667bda0f63308174f2cb76f15d93c54a9f67","transactionIndex":"0x2","blockHash":"0x7250d1dc6c4b7c1a51f13fb02a92cc60ab1b9592e457ad60813356c656593cc2","logIndex":"0x0","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x00000000000000000000000045d01cc478a3dcfd66607726dc50780f3eb4d7bc","0x0000000000000000000000000000000000000000000000000000002e90edd000"],"data":"0x","blockNumber":"0x1e8486","transactionHash":"0x0bf38cfac67554713083e8ad28b8b64c737a633af2f27b4b68b6033bf504929d","transactionIndex":"0x1","blockHash":"0xb2a862fb022e642626f152cd087ae1a895db9486051f22ece96e6b580f86e000","logIndex":"0x2","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026a","0x000000000000000000000000764b38935b4f1644e0ececae3308a314206edc75"],"data":"0x","blockNumber":"0x1e8493","transactionHash":"0xb7b856480e7112fc0e4e3d75870344fa17d42783e455a50255a978c8a7d44585","transactionIndex":"0x2","blockHash":"0xe417b01ee2ab21ede7f5ce2e15e6c65d7a61c22e5e87b5ac3024503e0764c2a1","logIndex":"0x0","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026b","0x000000000000000000000000580f3d001f78e76eee4ffe9284f7fa14c257ee59"],"data":"0x","blockNumber":"0x1e8493","transactionHash":"0x73dc8f424350d1371dce29a641b49bb49701b6984121594bbda11c4fbf0fb5d6","transactionIndex":"0x4","blockHash":"0xe417b01ee2ab21ede7f5ce2e15e6c65d7a61c22e5e87b5ac3024503e0764c2a1","logIndex":"0x1","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x000000000000000000000000caac46d9bd68bffb533320545a90cd92c6e98e58","0x00000000000000000000000000000000000000000000000000000034630b8a00"],"data":"0x","blockNumber":"0x1e8497","transactionHash":"0x627da1b5b7f911001b2a3bdc6df97a15298294a3e6f787c3ffa78b0225a046d2","transactionIndex":"0x1d","blockHash":"0xedb177b5137ecf5f7029c00b121de5f2ecfc94f0fa39687a029e118a9e652215","logIndex":"0x12","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x000000000000000000000000310d923ddbbee9ffa4d46addd6852d6d3b25c581","0x000000000000000000000000000000000000000000000000000000174876e800"],"data":"0x","blockNumber":"0x1e8498","transactionHash":"0x37aa1f411c2ef6926ea6b86d2b77a73604dcf001569afec20a9923ef6ceb2e51","transactionIndex":"0x3","blockHash":"0xaf32654f1abee523fb8881bc168d72cc7d9599c363dd9048735c7920541f61ec","logIndex":"0x2","removed":false},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x000000000000000000000000000000000000000000000000000000000000026c","0x000000000000000000000000140e7fac8258de95315830b979eaa1684404111b"],"data":"0x","blockNumber":"0x1e84a7","transactionHash":"0xecd29419a5cc2d96663ae9fe91fe8ce9f5d65dc0978f3ea5f0ea0caee115b04d","transactionIndex":"0x6","blockHash":"0xea7c7ad769c3424cb5965fe0e548e2b89d61a62d0a917dce0831cbc16d2f1a17","logIndex":"0x3","removed":false}]}
````
After running rpctest for a bit more, I made it crash

````
INFO [09-27|06:42:20.320] HTTP endpoint opened                     url=192.168.1.238:8545 ws=false
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fbd08052000 pc=0xd7f19c]

runtime stack:
runtime.throw(0x105f0ec, 0x2a)
	runtime/panic.go:1116 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:704 +0x4ac

goroutine 5443 [syscall]:
runtime.cgocall(0xd66d80, 0xc000355590, 0xc0004ea000)
	runtime/cgocall.go:133 +0x5b fp=0xc000355560 sp=0xc000355528 pc=0x4236db
github.com/RoaringBitmap/gocroaring._Cfunc_roaring_advance_uint32_iterator(0x7fbcf804bdc0, 0x7fbcf804bd00)
	_cgo_gotypes.go:197 +0x46 fp=0xc000355590 sp=0xc000355560 pc=0xbbe0a6
github.com/RoaringBitmap/gocroaring.(*intIterator).Next.func1(0xc000c73eb0, 0x987ca260b8ea6301)
	github.com/RoaringBitmap/gocroaring@v0.2.66-0.20200924122238-23640c9075eb/gocroaring.go:298 +0x55 fp=0xc0003555c8 sp=0xc000355590 pc=0xbc3295
github.com/RoaringBitmap/gocroaring.(*intIterator).Next(0xc000c73eb0, 0xc000bac001)
	github.com/RoaringBitmap/gocroaring@v0.2.66-0.20200924122238-23640c9075eb/gocroaring.go:298 +0x45 fp=0xc0003555f0 sp=0xc0003555c8 pc=0xbc1085
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GetLogs(0xc00007eaa0, 0x11b1cc0, 0xc000b873c0, 0x0, 0xc000ba45e0, 0xc000ba4600, 0xc000b9e3e0, 0x1, 0x1, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/get_receipts.go:187 +0x7ce fp=0xc000355850 sp=0xc0003555f0 pc=0xd5fcce
runtime.call256(0xc000383110, 0xc000010898, 0xc000b90e10, 0x6000000088)
	runtime/asm_amd64.s:543 +0x5c fp=0xc000355960 sp=0xc000355850 pc=0x48ed3c
reflect.Value.call(0xc0000ba980, 0xc000010898, 0x13, 0x1035e2c, 0x4, 0xc000b8eb90, 0x3, 0x3, 0xc000b8ebc0, 0xc000ba45c0, ...)
	reflect/value.go:475 +0x8c7 fp=0xc000355b78 sp=0xc000355960 pc=0x50c2e7
reflect.Value.Call(0xc0000ba980, 0xc000010898, 0x13, 0xc000b8eb90, 0x3, 0x3, 0x16, 0x0, 0x0)
	reflect/value.go:336 +0xb9 fp=0xc000355bf8 sp=0xc000355b78 pc=0x50b7d9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc00007d140, 0x11b1cc0, 0xc000b873c0, 0xc00099d4d3, 0xb, 0xc000ba45c0, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5 fp=0xc000355d00 sp=0xc000355bf8 pc=0xb4db25
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc000b90cf0, 0x11b1cc0, 0xc000b873c0, 0xc00041c310, 0xc00007d140, 0xc000ba45c0, 0x1, 0x1, 0x1)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:388 +0x8a fp=0xc000355d70 sp=0xc000355d00 pc=0xb47c4a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc000b90cf0, 0xc000b89d70, 0xc00041c310, 0xc000a0c6c0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:336 +0x294 fp=0xc000355e28 sp=0xc000355d70 pc=0xb47034
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc000b90cf0, 0xc000b89d70, 0xc00041c310, 0x119f801)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:298 +0x1be fp=0xc000355ef8 sp=0xc000355e28 pc=0xb4635e
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc000b89d70)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:139 +0x46 fp=0xc000355f68 sp=0xc000355ef8 pc=0xb51d86
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc000b90cf0, 0xc000ba4580)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:226 +0xd2 fp=0xc000355fd0 sp=0xc000355f68 pc=0xb51f52
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc000355fd8 sp=0xc000355fd0 pc=0x490541
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:222 +0x66

goroutine 1 [chan receive, 10 minutes]:
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/cli.StartRpcServer(0x11b1cc0, 0xc0002823c0, 0x7ffd7d053707, 0x12, 0x0, 0x0, 0x7ffd7d05374a, 0xd, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/cli/config.go:133 +0x62c
main.main.func1(0x195eee0, 0xc0000ba300, 0x0, 0x8, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/main.go:28 +0x2f0
github.com/spf13/cobra.(*Command).execute(0x195eee0, 0xc0000320a0, 0x8, 0x8, 0x195eee0, 0xc0000320a0)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x195eee0, 0xc0002823c0, 0xc0003fdf78, 0x426125)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.0.0/command.go:880
main.main()
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/main.go:34 +0xea

goroutine 9 [chan receive]:
github.com/ledgerwatch/turbo-geth/metrics.(*meterArbiter).tick(0x1a70640)
	github.com/ledgerwatch/turbo-geth/metrics/meter.go:290 +0x7d
created by github.com/ledgerwatch/turbo-geth/metrics.NewMeterForced
	github.com/ledgerwatch/turbo-geth/metrics/meter.go:71 +0x105

goroutine 10 [select]:
github.com/ledgerwatch/turbo-geth/consensus/ethash.(*remoteSealer).loop(0xc0002b0000)
	github.com/ledgerwatch/turbo-geth/consensus/ethash/sealer.go:279 +0x25c
created by github.com/ledgerwatch/turbo-geth/consensus/ethash.startRemoteSealer
	github.com/ledgerwatch/turbo-geth/consensus/ethash/sealer.go:263 +0x2b2

goroutine 26 [select, 10 minutes]:
github.com/ledgerwatch/turbo-geth/cmd/utils.RootContext.func1(0xc0002149d0, 0x11b1cc0, 0xc0002823c0)
	github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:344 +0x1c5
created by github.com/ledgerwatch/turbo-geth/cmd/utils.RootContext
	github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:335 +0x7d

goroutine 27 [chan receive, 10 minutes]:
github.com/ledgerwatch/turbo-geth/internal/debug.SetupCobra.func1()
	github.com/ledgerwatch/turbo-geth/internal/debug/flags.go:184 +0xb6
created by github.com/ledgerwatch/turbo-geth/internal/debug.SetupCobra
	github.com/ledgerwatch/turbo-geth/internal/debug/flags.go:181 +0x385

goroutine 38 [syscall, 10 minutes]:
os/signal.signal_recv(0x490541)
	runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x45

goroutine 28 [select, 10 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000282540)
	google.golang.org/grpc@v1.32.0/balancer_conn_wrappers.go:69 +0xc8
created by google.golang.org/grpc.newCCBalancerWrapper
	google.golang.org/grpc@v1.32.0/balancer_conn_wrappers.go:60 +0x172

goroutine 29 [chan receive, 10 minutes]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc0000e8000)
	google.golang.org/grpc@v1.32.0/clientconn.go:1173 +0x709
created by google.golang.org/grpc.(*addrConn).connect
	google.golang.org/grpc@v1.32.0/clientconn.go:813 +0x12a

goroutine 55 [IO wait]:
internal/poll.runtime_pollWait(0x7fbd143e17b8, 0x72, 0x11973c0)
	runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc00021e198, 0x72, 0xc000568000, 0x8000, 0x8000)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00021e180, 0xc000568000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc00021e180, 0xc000568000, 0x8000, 0x8000, 0x95d4fe, 0x800010601, 0x0)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000216020, 0xc000568000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	net/net.go:182 +0x8e
bufio.(*Reader).Read(0xc00032e480, 0xc00023a038, 0x9, 0x9, 0xc000202000, 0x7fbd3e6c4c28, 0x0)
	bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1194520, 0xc00032e480, 0xc00023a038, 0x9, 0x9, 0x9, 0x7a218daafb9d6, 0xc00006de48, 0x4b671a)
	io/io.go:314 +0x87
io.ReadFull(...)
	io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc00023a038, 0x9, 0x9, 0x1194520, 0xc00032e480, 0x0, 0x8d00000000, 0x1a70da0, 0x8e1c)
	golang.org/x/net@v0.0.0-20200625001655-4c5254603344/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00023a000, 0xc00030ae40, 0xc00030ae40, 0x0, 0x0)
	golang.org/x/net@v0.0.0-20200625001655-4c5254603344/http2/frame.go:492 +0xa5
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0001a2000)
	google.golang.org/grpc@v1.32.0/internal/transport/http2_client.go:1294 +0x179
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	google.golang.org/grpc@v1.32.0/internal/transport/http2_client.go:310 +0x1071

goroutine 30 [IO wait]:
internal/poll.runtime_pollWait(0x7fbd143e16d8, 0x72, 0x0)
	runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0000bb198, 0x72, 0x0, 0x0, 0x1039317)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000bb180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc0000bb180, 0x5a26ec27f2f7cbc, 0x0, 0x0)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000389fa0, 0x5f7036a6, 0xc0001efe68, 0x4b6cc6)
	net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000389fa0, 0xc0001efeb8, 0x18, 0xc000204f00, 0x91a1ec)
	net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00037e540, 0x11ae580, 0xc000389fa0, 0x0, 0x0)
	net/http/server.go:2937 +0x266
created by github.com/ledgerwatch/turbo-geth/node.StartHTTPEndpoint
	github.com/ledgerwatch/turbo-geth/node/endpoints.go:47 +0x12c

goroutine 56 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00022e0f0, 0x1, 0x0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:395 +0x125
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00032e600, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:515 +0x1d3
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0001a2000)
	google.golang.org/grpc@v1.32.0/internal/transport/http2_client.go:356 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	google.golang.org/grpc@v1.32.0/internal/transport/http2_client.go:354 +0x123c

goroutine 5445 [select]:
google.golang.org/grpc.newClientStream.func5(0xc0001c9c00, 0xc000b93560, 0x11b1d80, 0xc000bc00c0)
	google.golang.org/grpc@v1.32.0/stream.go:318 +0xda
created by google.golang.org/grpc.newClientStream
	google.golang.org/grpc@v1.32.0/stream.go:317 +0xbd0

goroutine 3984 [semacquire]:
sync.runtime_Semacquire(0xc000b90d20)
	runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000b90d18)
	sync/waitgroup.go:130 +0x65
github.com/ledgerwatch/turbo-geth/rpc.(*handler).close(0xc000b90cf0, 0x11948e0, 0xc000070040, 0x0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:154 +0x65
github.com/ledgerwatch/turbo-geth/rpc.(*Server).serveSingleRequest(0xc0001cbf50, 0x11b1d80, 0xc000b89c20, 0x11b48c0, 0xc000b8eaf0)
	github.com/ledgerwatch/turbo-geth/rpc/server.go:116 +0x286
github.com/ledgerwatch/turbo-geth/rpc.(*Server).ServeHTTP(0xc0001cbf50, 0x11ad400, 0xc000ba44a0, 0xc000bae000)
	github.com/ledgerwatch/turbo-geth/rpc/http.go:254 +0x43c
github.com/ledgerwatch/turbo-geth/node.(*virtualHostHandler).ServeHTTP(0xc000389f60, 0x11ad400, 0xc000ba44a0, 0xc000bae000)
	github.com/ledgerwatch/turbo-geth/node/rpcstack.go:374 +0x205
github.com/ledgerwatch/turbo-geth/node.newGzipHandler.func1(0x11ae840, 0xc000d72540, 0xc000bae000)
	github.com/ledgerwatch/turbo-geth/node/rpcstack.go:426 +0x2f7
net/http.HandlerFunc.ServeHTTP(0xc000389f80, 0x11ae840, 0xc000d72540, 0xc000bae000)
	net/http/server.go:2042 +0x44
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/cli.StartRpcServer.func1(0x11ae840, 0xc000d72540, 0xc000bae000)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/cli/config.go:118 +0x85
net/http.HandlerFunc.ServeHTTP(0xc0001984b0, 0x11ae840, 0xc000d72540, 0xc000bae000)
	net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc00037e540, 0x11ae840, 0xc000d72540, 0xc000bae000)
	net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0003d8280, 0x11b1cc0, 0xc000982c80)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36c

goroutine 5446 [select]:
google.golang.org/grpc.newClientStream.func5(0xc0001c9c00, 0xc000b937a0, 0x11b1d80, 0xc000bc0420)
	google.golang.org/grpc@v1.32.0/stream.go:318 +0xda
created by google.golang.org/grpc.newClientStream
	google.golang.org/grpc@v1.32.0/stream.go:317 +0xbd0

goroutine 5442 [IO wait]:
internal/poll.runtime_pollWait(0x7fbd143e15f8, 0x72, 0x11973c0)
	runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000138598, 0x72, 0xc0005ff900, 0x1, 0x1)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000138580, 0xc0005ff991, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc000138580, 0xc0005ff991, 0x1, 0x1, 0xc0000702f0, 0x1, 0xc000506f00)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005aa0e0, 0xc0005ff991, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:182 +0x8e
net/http.(*connReader).backgroundRead(0xc0005ff980)
	net/http/server.go:690 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:686 +0xd5

goroutine 5474 [select]:
google.golang.org/grpc.newClientStream.func5(0xc0001c9c00, 0xc000b02d80, 0x11b1d80, 0xc000b1c3f0)
	google.golang.org/grpc@v1.32.0/stream.go:318 +0xda
created by google.golang.org/grpc.newClientStream
	google.golang.org/grpc@v1.32.0/stream.go:317 +0xbd0

goroutine 5444 [select]:
google.golang.org/grpc.newClientStream.func5(0xc0001c9c00, 0xc000b93320, 0x11b1d80, 0xc000b89f50)
	google.golang.org/grpc@v1.32.0/stream.go:318 +0xda
created by google.golang.org/grpc.newClientStream
	google.golang.org/grpc@v1.32.0/stream.go:317 +0xbd0

goroutine 5430 [select]:
google.golang.org/grpc.newClientStream.func5(0xc0001c9c00, 0xc000940fc0, 0x11b1d80, 0xc0009379e0)
	google.golang.org/grpc@v1.32.0/stream.go:318 +0xda
created by google.golang.org/grpc.newClientStream
	google.golang.org/grpc@v1.32.0/stream.go:317 +0xbd0
````

**Comment by AskAlexSharov** [comment]
fixed both
