### ISSUE TITLE
trace_filter crashed - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#1146]
I'm running on ubuntu 18.04 LTS with commit 64e1a8f

```
ERROR[09-27|20:03:13.021] RPC method trace_filter crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 1144408214 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc0007159e4, 0xc, 0xc00014fd28)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xba
panic(0xec78e0, 0x1909590)
        runtime/panic.go:969 +0x175
github.com/ledgerwatch/turbo-geth/core/types.(*Block).Transactions(...)
        github.com/ledgerwatch/turbo-geth/core/types/block.go:336
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*TraceAPIImpl).Filter.func3(0x118aca0, 0xc0004713b0, 0x427af8, 0x90)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/trace_api.go:211 +0x2eb
github.com/ledgerwatch/turbo-geth/ethdb.(*RemoteKV).View(0xc00030e540, 0x117dfc0, 0xc000550b80, 0xc000280c60, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/ethdb/kv_remote.go:219 +0x9e
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*TraceAPIImpl).Filter(0xc0000ab440, 0x117dfc0, 0xc000550b80, 0xc000715a18, 0xc000715a20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/trace_api.go:152 +0x377
reflect.Value.call(0xc000235300, 0xc000316ab8, 0x13, 0x10026ac, 0x4, 0xc000618910, 0x3, 0x3, 0xc000618940, 0xc0002ad5a0, ...)
        reflect/value.go:475 +0x8c7
reflect.Value.Call(0xc000235300, 0xc000316ab8, 0x13, 0xc000618910, 0x3, 0x3, 0x16, 0x0, 0x0)
        reflect/value.go:336 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc00030fe60, 0x117dfc0, 0xc000550b80, 0xc0007159e4, 0xc, 0xc0002ad5a0, 0x1, 0x1, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc000280990, 0x117dfc0, 0xc000550b80, 0xc0002fea10, 0xc00030fe60, 0xc0002ad5a0, 0x1, 0x1, 0x1)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:388 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc000280990, 0xc000471350, 0xc0002fea10, 0xf7e140)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:336 +0x294
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc000280990, 0xc000471350, 0xc0002fea10, 0xc000316240)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:298 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleBatch.func2(0xc000471350)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:119 +0xf3
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc000280990, 0xc000550b40)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:226 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:222 +0x66

WARN [09-27|20:03:13.021] Served                                   conn=127.0.0.1:41198      method=trace_filter              reqid=12898647 t="309.496µs"  err="method handler crashed"
```

Can i restart turbogeth or do i need to extra more info beforehand ?

**Comment by tjayrush** [comment]
Can you provide a `curl` command to reproduce?

**Comment by koen84** [comment]
Sadly when i went digging for it server had become unresponsive and i had to reset.  Sorry, i wish i could be more helpful.

**Comment by koen84** [comment]
Actually, looks like this was the request that made it crash
`DBG Request: {"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0x8d196b","toBlock":"0x8d196b"}],"id":677484}`

**Comment by tjayrush** [comment]
Thanks for that. I tried this `curl` command against the latest build

```
curl --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0x8d196b","toBlock":"0x8d196b"}],"id":677484}' -H "Content-Type: application/json" -X POST localhost:8545
```
I'm not seeing a crash on my Mac. (What operating system are you on?)

One thing I do see in the stack trace is this:

```
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/trace_api.go:211
```

When I look for at [that file on the latest master branch](https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/trace_api.go), I see that the file doesn't have 211 lines.

The first thing to do is `git pull` the latest code and then run the above command.

In answer to this:

"Can i restart turbogeth or do i need to extra more info beforehand ?"

Yes. After `git pull` and rebuilding, you'll have to restart.

**Comment by tjayrush** [comment]
@koen84 Did you have a chance to try this on the latest master branch?

**Comment by tjayrush** [comment]
I spent some time looking at this issue. It no longer crashes, but the example is VERY slow. We have the performance issue documented here #1128.

Unless I hear otherwise, I will close this issue shortly.
