### ISSUE TITLE
MDBX sync does not quit when I send term signal to TG

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1312]
This is what I am left with:
````
INFO [10-28|00:14:49.723] Blockchain stopped
WARN [10-28|00:14:49.773] Synchronisation failed, retrying         err=stopped
INFO [10-28|00:14:49.776] Ethereum protocol stopped
WARN [10-28|00:14:49.776] error while stopping transaction pool    err="transaction pool is already stopped"
INFO [10-28|00:14:49.779] database closed (LMDB)                   lmdb=nodes
SIGABRT: abort
PC=0x4a6781 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x2172528, 0x80, 0x0, 0x0, 0x2123f9c400000000, 0x427a59e501ebfd73, 0xec56493b494c30f, 0x719ad37cac39c136, 0x7ffeefd61ab0, 0x44027f, ...)
        runtime/sys_linux_amd64.s:587 +0x21
runtime.futexsleep(0x2172528, 0x0, 0xffffffffffffffff)
        runtime/os_linux.go:45 +0x46
runtime.notesleep(0x2172528)
        runtime/lock_futex.go:159 +0x9f
runtime.stopm()
        runtime/proc.go:1910 +0xc5
runtime.exitsyscall0(0xc000602600)
        runtime/proc.go:3401 +0x11d
runtime.mcall(0x11cf3c0)
        runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, 2155 minutes]:
github.com/ledgerwatch/turbo-geth/node.(*Node).Wait(...)
        github.com/ledgerwatch/turbo-geth/node/node.go:414
github.com/ledgerwatch/turbo-geth/turbo/node.(*TurboGethNode).Serve(0xc000240670, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/turbo/node/node.go:42 +0x85
main.runTurboGeth(0xc000146000)
        github.com/ledgerwatch/turbo-geth/cmd/tg/main.go:47 +0x236
github.com/urfave/cli.HandleAction(0x1297e60, 0x157cc20, 0xc000146000, 0xc000146000, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:528 +0x58
github.com/urfave/cli.(*App).Run(0xc000196000, 0xc0000c8000, 0x9, 0x9, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:288 +0x655
main.main()
        github.com/ledgerwatch/turbo-geth/cmd/tg/main.go:24 +0x87


goroutine 36 [sync.Cond.Wait, 2155 minutes]:
runtime.goparkunlock(...)
        runtime/proc.go:312
sync.runtime_notifyListWait(0xc000244f20, 0xc000000000)
        runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000244f10)
        sync/cond.go:56 +0x9d
github.com/anacrolix/stm.(*Tx).wait(0xc000244ee0)
        github.com/anacrolix/stm@v0.2.0/tx.go:45 +0x131
github.com/anacrolix/stm.Atomically(0xc000070e70, 0xc000070e70, 0x21707c0)
        github.com/anacrolix/stm@v0.2.0/funcs.go:51 +0x138
github.com/anacrolix/stm/rate.(*Limiter).tokenGenerator(0xc0003e6680, 0x2625a00)
        github.com/anacrolix/stm@v0.2.0/rate/ratelimit.go:59 +0x1d7
created by github.com/anacrolix/stm/rate.NewLimiter
        github.com/anacrolix/stm@v0.2.0/rate/ratelimit.go:45 +0x315

goroutine 8 [chan receive]:
github.com/ledgerwatch/turbo-geth/metrics.(*meterArbiter).tick(0x216ed60)
        github.com/ledgerwatch/turbo-geth/metrics/meter.go:292 +0x7d
created by github.com/ledgerwatch/turbo-geth/metrics.NewMeterForced
        github.com/ledgerwatch/turbo-geth/metrics/meter.go:71 +0x105

goroutine 9 [select]:
github.com/ledgerwatch/turbo-geth/consensus/ethash.(*remoteSealer).loop(0xc0000f2000)
        github.com/ledgerwatch/turbo-geth/consensus/ethash/sealer.go:279 +0x25c
created by github.com/ledgerwatch/turbo-geth/consensus/ethash.startRemoteSealer
        github.com/ledgerwatch/turbo-geth/consensus/ethash/sealer.go:263 +0x2b2

goroutine 53 [syscall]:
os/signal.signal_recv(0x16cb320)
        runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        os/signal/signal.go:150 +0x45

goroutine 40 [chan receive, 2155 minutes]:
github.com/JekaMas/notify.(*nonrecursiveTree).dispatch(0xc00007c480, 0xc00007c2a0)
        github.com/JekaMas/notify@v0.9.4/tree_nonrecursive.go:36 +0xb6
created by github.com/JekaMas/notify.newNonrecursiveTree
        github.com/JekaMas/notify@v0.9.4/tree_nonrecursive.go:29 +0xe5

goroutine 29 [select, 2155 minutes]:
github.com/ledgerwatch/turbo-geth/accounts/keystore.(*watcher).loop(0xc00000fca0)
        github.com/ledgerwatch/turbo-geth/accounts/keystore/watch.go:107 +0x485
created by github.com/ledgerwatch/turbo-geth/accounts/keystore.(*watcher).start
        github.com/ledgerwatch/turbo-geth/accounts/keystore/watch.go:56 +0x59

goroutine 30 [select]:
github.com/ledgerwatch/turbo-geth/accounts/keystore.(*KeyStore).updater(0xc0001ea780)
        github.com/ledgerwatch/turbo-geth/accounts/keystore/keystore.go:203 +0xda
created by github.com/ledgerwatch/turbo-geth/accounts/keystore.(*KeyStore).Subscribe
        github.com/ledgerwatch/turbo-geth/accounts/keystore/keystore.go:190 +0x12f

goroutine 31 [select, 2155 minutes]:
github.com/ledgerwatch/turbo-geth/accounts.(*Manager).update(0xc0001ec410)
        github.com/ledgerwatch/turbo-geth/accounts/manager.go:118 +0x1a6
created by github.com/ledgerwatch/turbo-geth/accounts.NewManager
        github.com/ledgerwatch/turbo-geth/accounts/manager.go:79 +0x4e5

goroutine 41 [chan receive, 2155 minutes]:
github.com/JekaMas/notify.(*nonrecursiveTree).internal(0xc00007c480, 0xc00007c3c0)
        github.com/JekaMas/notify@v0.9.4/tree_nonrecursive.go:81 +0x58
created by github.com/JekaMas/notify.newNonrecursiveTree
        github.com/JekaMas/notify@v0.9.4/tree_nonrecursive.go:30 +0x111

goroutine 42 [syscall, 2155 minutes]:
syscall.Syscall6(0xe8, 0x8, 0xc0002b5f9c, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        syscall/asm_linux_amd64.s:41 +0x5
golang.org/x/sys/unix.EpollWait(0x8, 0xc0002b5f9c, 0x1, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        golang.org/x/sys@v0.0.0-20200909081042-eff7692f9009/unix/zsyscall_linux_amd64.go:76 +0x72
github.com/JekaMas/notify.(*inotify).loop(0xc00069c000, 0xc0002ae000)
        github.com/JekaMas/notify@v0.9.4/watcher_inotify.go:194 +0x79
created by github.com/JekaMas/notify.(*inotify).lazyinit
        github.com/JekaMas/notify@v0.9.4/watcher_inotify.go:134 +0x145

goroutine 43 [chan receive, 2155 minutes]:
github.com/JekaMas/notify.(*inotify).send(0xc00069c000, 0xc0002ae000)
        github.com/JekaMas/notify@v0.9.4/watcher_inotify.go:254 +0xab
created by github.com/JekaMas/notify.(*inotify).lazyinit
        github.com/JekaMas/notify@v0.9.4/watcher_inotify.go:137 +0x19a

goroutine 44 [chan receive, 2155 minutes]:
github.com/JekaMas/notify.(*inotify).send(0xc00069c000, 0xc0002ae000)
        github.com/JekaMas/notify@v0.9.4/watcher_inotify.go:254 +0xab
created by github.com/JekaMas/notify.(*inotify).lazyinit
        github.com/JekaMas/notify@v0.9.4/watcher_inotify.go:137 +0x19a

goroutine 77 [select]:
github.com/ledgerwatch/turbo-geth/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc0002df270)
        github.com/ledgerwatch/turbo-geth/eth/filters/api.go:84 +0x1db
created by github.com/ledgerwatch/turbo-geth/eth/filters.NewPublicFilterAPI
        github.com/ledgerwatch/turbo-geth/eth/filters/api.go:73 +0x131

goroutine 90 [chan receive]:
github.com/ledgerwatch/turbo-geth/cmd/utils.StartNode.func1(0xc00038ed20)
        github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:84 +0x199
created by github.com/ledgerwatch/turbo-geth/cmd/utils.StartNode
        github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:76 +0xad

goroutine 1513027 [syscall]:
github.com/ledgerwatch/turbo-geth/ethdb/mdbx._Cfunc_mdbx_env_close(0x281b590, 0x0)
        _cgo_gotypes.go:555 +0x49
github.com/ledgerwatch/turbo-geth/ethdb/mdbx.(*Env).close.func1(0xc0001b33e0, 0xc000723e10)
        github.com/ledgerwatch/turbo-geth/ethdb/mdbx/env.go:205 +0x55
github.com/ledgerwatch/turbo-geth/ethdb/mdbx.(*Env).close(0xc0001b33e0, 0x4)
        github.com/ledgerwatch/turbo-geth/ethdb/mdbx/env.go:205 +0x53
github.com/ledgerwatch/turbo-geth/ethdb/mdbx.(*Env).Close(0xc0001b33e0, 0x217d160, 0x217d170)
        github.com/ledgerwatch/turbo-geth/ethdb/mdbx/env.go:221 +0x2f
github.com/ledgerwatch/turbo-geth/ethdb.(*MdbxKV).Close(0xc0004a4ae0)
        github.com/ledgerwatch/turbo-geth/ethdb/kv_mdbx.go:239 +0x5c
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Close(0xc0001b34a0)
        github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:288 +0x33
github.com/ledgerwatch/turbo-geth/node.(*Node).doClose(0xc00038ed20, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/node/node.go:227 +0xa8
github.com/ledgerwatch/turbo-geth/node.(*Node).Close(0xc00038ed20, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/node/node.go:212 +0x17a
created by github.com/ledgerwatch/turbo-geth/cmd/utils.StartNode.func1
        github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:82 +0x16a

rax    0xca
rbx    0x21723e0
rcx    0x4a6783
rdx    0x0
rdi    0x2172528
rsi    0x80
rbp    0x7ffeefd61a78
rsp    0x7ffeefd61a30
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xffffffffffffffff
r13    0x21
r14    0x20
r15    0x66
rip    0x4a6781
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
````

**Comment by AskAlexSharov** [comment]
Can reproduce on mac:
1. After cancelation I see "Looking for peers" - means `srv.setupDialScheduler` doesn't stop also: fixing it by https://github.com/ledgerwatch/turbo-geth/pull/1334
2. trying more...
