### ISSUE TITLE
Crash when stopped syncing

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1533]
Running from current master

````
INFO [03-02|18:28:07.669] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=f8d14e14... alloc=885.62MiB sys=4.09GiB numGC=249
INFO [03-02|18:28:37.669] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=fd02530c... alloc=972.70MiB sys=4.09GiB numGC=249
INFO [03-02|18:29:04.965] [12/14 TxLookup] DONE                    in=24m57.213324615s
INFO [03-02|18:29:04.965] [13/14 TxPool] Starting tx pool after sync from=11928427 to=11960292
INFO [03-02|18:29:04.967] Loaded local transaction journal         transactions=0 dropped=0
INFO [03-02|18:29:04.967] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-02|18:29:04.967] transaction pool started
INFO [03-02|18:29:05.597] [13/14 TxPool] Read canonical hashes     hashes=31865
INFO [03-02|18:30:01.008] [13/14 TxPool] Transaction stats         pending=0 queued=0
INFO [03-02|18:30:01.008] [13/14 TxPool] DONE                      in=56.04321977s
INFO [03-02|18:30:01.008] [14/14 Finish] Update current block for the RPC API to=11960292
INFO [03-02|18:30:01.008] event subscription channel closed with the RPC daemon
INFO [03-02|18:30:01.008] event subscription channel closed with the RPC daemon
panic: runtime error: slice bounds out of range [2:1]

goroutine 819 [running]:
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*Events).OnNewHeader(0xc00068ecc0, 0x3c032ad0780)
	github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/events.go:31 +0x1ed
github.com/ledgerwatch/turbo-geth/eth/stagedsync.NotifyRpcDaemon(0xb6036c, 0xb67fe4, 0x5423c00, 0xc00068ecc0, 0x545b660, 0xc000b02cc0, 0x2, 0x2)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_finish.go:25 +0x72
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DefaultStages.func14.1(0x3c00c685c50, 0x54239c0, 0xc00028d5c0, 0x6, 0x4840bac8)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagebuilder.go:360 +0x23b
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc00028d5c0, 0xc0000c2d20, 0xb50fb38, 0xc0005c29c0, 0x4840bac8, 0xc000b02cc0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:270 +0x155
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc00028d5c0, 0x4840ba38, 0xc0005c29c0, 0x4840ba80, 0xc000b02cc0, 0xc000580ca8, 0x545b5c0)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:201 +0x348
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc0002c4000, 0xc000818000, 0x4a8feca7962d2638, 0x549667dda8f7548, 0xc85a402de5a8621a, 0x84b7d0ebb4c4846f, 0xb67fe2, 0xc0003286c0, 0xc000b164b0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:622 +0xcc5
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc0002c4000, 0xc000788640, 0x10, 0x4a8feca7962d2638, 0x549667dda8f7548, 0xc85a402de5a8621a, 0x84b7d0ebb4c4846f, 0xb67fe2, 0x1, 0xc0003286c0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:466 +0x3a5
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc0002c4000, 0xc000788640, 0x10, 0x4a8feca7962d2638, 0x549667dda8f7548, 0xc85a402de5a8621a, 0x84b7d0ebb4c4846f, 0xb67fe2, 0x1, 0xc0003286c0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:376 +0xa6
github.com/ledgerwatch/turbo-geth/eth.(*ProtocolManager).doSync(0xc0001ae2c0, 0xc000570f80, 0x0, 0x1)
	github.com/ledgerwatch/turbo-geth/eth/sync.go:315 +0x112
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync.func1(0xc00056cf90, 0xc000570f80)
	github.com/ledgerwatch/turbo-geth/eth/sync.go:286 +0x38
created by github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync
	github.com/ledgerwatch/turbo-geth/eth/sync.go:286 +0x76
````

**Comment by AlexeyAkhunov** [comment]
Fixed by https://github.com/ledgerwatch/turbo-geth/pull/1531
