### ISSUE TITLE
TG crashes on startup (mining stage?)

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1590]
````
INFO [03-23|09:06:55.131] Build info                               git_branch=master git_commit=aff859edc028dc5c4abc102caa54f8c420bbf3ba
INFO [03-23|09:06:55.131] Starting Turbo-Geth on Ethereum mainnet...
INFO [03-23|09:06:55.131] Bumping default cache on mainnet         provided=0 updated=4096
INFO [03-23|09:06:55.132] Dropping default light client cache      provided=0 updated=128
INFO [03-23|09:06:55.132] Maximum peer count                       ETH=50 total=50
INFO [03-23|09:06:55.135] Enabling recording of key preimages since archive mode is used
INFO [03-23|09:06:55.135] Set global gas cap                       cap=25000000
INFO [03-23|09:06:55.135] Opening Database (LMDB)                  mapSize="2.0 TB" maxFreelistReuse=1000
INFO [03-23|09:06:55.140] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, YOLO v3: <nil>, Engine: ethash}"
INFO [03-23|09:06:55.140] Disk storage enabled for ethash DAGs     dir=/Users/alexeysharp/Library/tg-ethash count=2
INFO [03-23|09:06:55.140] Initialising Ethereum protocol           network=1
INFO [03-23|09:06:55.147] Most recent local header                 number=12090335 hash="50fbf5…acbd2a" td=22342731394418462026623 age=14h19m16s
INFO [03-23|09:06:55.147] Most recent local block                  number=12090335 hash="50fbf5…acbd2a" td=22342731394418462026623 age=14h19m16s
WARN [03-23|09:06:55.147] Miner extra data exceed limit            extra=0xe08407e503028a747572626f2d6765746888676f312e31352e388664617277696e limit=32
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4cc088d]

goroutine 1 [running]:
github.com/ledgerwatch/turbo-geth/miner.(*Miner).SubscribePendingLogs(...)
	github.com/ledgerwatch/turbo-geth/miner/miner.go:210
github.com/ledgerwatch/turbo-geth/eth.(*EthAPIBackend).SubscribePendingLogsEvent(0xc000030b40, 0xc00002dce0, 0x53a6940, 0xc000030d80)
	github.com/ledgerwatch/turbo-geth/eth/api_backend.go:270 +0x2d
github.com/ledgerwatch/turbo-geth/eth/filters.NewEventSystem(0x53c9280, 0xc000030b40, 0xc0003cf600, 0x4b1468a)
	github.com/ledgerwatch/turbo-geth/eth/filters/filter_system.go:131 +0x2de
github.com/ledgerwatch/turbo-geth/eth/filters.NewPublicFilterAPI(0x53c9280, 0xc000030b40, 0xc000030d00, 0x45d964b800, 0x8)
	github.com/ledgerwatch/turbo-geth/eth/filters/api.go:67 +0x8e
github.com/ledgerwatch/turbo-geth/eth.(*Ethereum).APIs(0xc0003417c0, 0x1, 0x1, 0x53b0740)
	github.com/ledgerwatch/turbo-geth/eth/backend.go:590 +0xe5
github.com/ledgerwatch/turbo-geth/eth.New(0xc0003be700, 0x5c25440, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/eth/backend.go:501 +0x22a5
github.com/ledgerwatch/turbo-geth/cmd/utils.RegisterEthService(0xc0003be700, 0x5c25440, 0x5c25440)
	github.com/ledgerwatch/turbo-geth/cmd/utils/flags.go:1734 +0x39
github.com/ledgerwatch/turbo-geth/turbo/node.New(0xc000479760, 0xc00015c380, 0x53af000, 0x28, 0x536c0d0, 0x6, 0x0, 0x2)
	github.com/ledgerwatch/turbo-geth/turbo/node/node.go:84 +0xd0
main.runTurboGeth(0xc000479760)
	github.com/ledgerwatch/turbo-geth/cmd/tg/main.go:55 +0x3c7
github.com/urfave/cli.HandleAction(0x4f60f80, 0x5256610, 0xc000479760, 0xc000479760, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:528 +0x58
github.com/urfave/cli.(*App).Run(0xc000236700, 0xc00011a180, 0x3, 0x3, 0x0, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:288 +0x655
main.main()
	github.com/ledgerwatch/turbo-geth/cmd/tg/main.go:27 +0x87
````

**Comment by AskAlexSharov** [comment]
fixed
