### ISSUE TITLE
Panic in remotedbserver

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1623]
Not sure how to reproduce, but it involves RPC daemon

````
INFO [03-28|19:35:04.889] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=38d27821... alloc=303.03MiB sys=2.18GiB    numGC=284
INFO [03-28|19:35:34.888] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=59f4f8a8... alloc=336.58MiB sys=2.18GiB    numGC=284
INFO [03-28|19:36:29.560] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=710c77a2... alloc=263.14MiB sys=2.18GiB    numGC=285
INFO [03-28|19:36:34.887] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=77122a1c... alloc=270.21MiB sys=2.18GiB    numGC=285
INFO [03-28|19:37:04.887] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=97d8af9d... alloc=311.02MiB sys=2.18GiB    numGC=285
INFO [03-28|19:38:05.695] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=b475624f... alloc=358.50MiB sys=2.18GiB    numGC=285
INFO [03-28|19:38:34.889] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=d22b4f6c... alloc=275.11MiB sys=2.18GiB    numGC=286
INFO [03-28|19:39:07.281] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=df9018cc... alloc=298.21MiB sys=2.18GiB    numGC=286
INFO [03-28|19:39:34.883] [12/14 TxLookup] ETL [2/2] Loading       into=l               current key=fc464da5... alloc=327.93MiB sys=2.18GiB    numGC=286
INFO [03-28|19:40:20.635] Batch                                    commit=41.812404793s
INFO [03-28|19:40:20.636] [12/14 TxLookup] DONE                    in=6m21.313109937s
INFO [03-28|19:40:20.636] [13/14 TxPool] Starting tx pool after sync from=12122150 to=12129153
INFO [03-28|19:40:20.637] Loaded local transaction journal         transactions=0 dropped=0
INFO [03-28|19:40:20.637] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-28|19:40:20.637] transaction pool started
INFO [03-28|19:40:20.638] [13/14 TxPool] Read canonical hashes     hashes=7003
INFO [03-28|19:40:24.364] [13/14 TxPool] Transaction stats         pending=0 queued=0
INFO [03-28|19:40:24.365] [14/14 Finish] Update current block for the RPC API to=12129153
INFO [03-28|19:40:24.365] event subscription channel closed with the RPC daemon
panic: sync: negative WaitGroup counter

goroutine 1673 [running]:
sync.(*WaitGroup).Add(0x3c01160e6b0, 0xffffffffffffffff)
	sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(...)
	sync/waitgroup.go:99
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*EthBackendServer).Subscribe.func1(0xc003644480, 0x51bc5a0, 0xc000180210)
	github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/ethbackend.go:75 +0x32e
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*Events).OnNewHeader(0xc000400c30, 0xc003644480)
	github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/events.go:31 +0x75
github.com/ledgerwatch/turbo-geth/eth/stagedsync.NotifyNewHeaders(0xb8f827, 0xb91381, 0x51cb280, 0xc000400c30, 0x51e9670, 0xc0004ad040, 0x2, 0x2)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_finish.go:21 +0x52
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DefaultStages.func14.1(0xc0018dafc0, 0x51bccc0, 0xc000307f20, 0x6, 0x51d2588)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagebuilder.go:388 +0x23e
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc000307f20, 0xc0001a2c80, 0x51d2588, 0xc0004ad040, 0x51d2588, 0xc0004ad040, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:270 +0x15d
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc000307f20, 0x9f95188, 0xc0004ad040, 0x9f95188, 0xc0004ad040, 0xc0004ec828, 0x51e9670)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:201 +0x34b
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc00058c200, 0xc000204690, 0xa8a540610511ad3f, 0xee7fc16b16cf9005, 0xa28b22a6e96ef13a, 0x7c9fec7b859a394, 0xb9137b, 0xc00013efc0, 0x508f4b0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:608 +0xe05
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc00058c200, 0xc0004c7000, 0x40, 0xa8a540610511ad3f, 0xee7fc16b16cf9005, 0xa28b22a6e96ef13a, 0x7c9fec7b859a394, 0xb9137b, 0x1, 0xc00013efc0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:450 +0x3a5
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc00058c200, 0xc0004c7000, 0x40, 0xa8a540610511ad3f, 0xee7fc16b16cf9005, 0xa28b22a6e96ef13a, 0x7c9fec7b859a394, 0xb9137b, 0xc000000001, 0xc00013efc0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:365 +0xa9
github.com/ledgerwatch/turbo-geth/eth.(*handler).doSync(0xc00042e280, 0xc0004c4180, 0x40465d6, 0x50925e8)
	github.com/ledgerwatch/turbo-geth/eth/sync.go:291 +0xcb
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync.func1(0xc000338090, 0xc0004c4180)
	github.com/ledgerwatch/turbo-geth/eth/sync.go:284 +0x38
created by github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync
	github.com/ledgerwatch/turbo-geth/eth/sync.go:284 +0x76

````

**Comment by AskAlexSharov** [comment]
Fixed in https://github.com/ledgerwatch/turbo-geth/pull/1625
