### ISSUE TITLE
Panic during block execution

### ISSUE THREAD

**Issue by pipermerriam** [ledgerwatch/turbo-geth#1634]
#### System information

Geth version: 3da261ba9b3ecc7fd446a8b5d2c0abce0cbecbf2
OS & Version: Linux
Commit hash : 3da261ba9b3ecc7fd446a8b5d2c0abce0cbecbf2

#### Expected behaviour

Execution to.... execute

#### Actual behaviour

Client crashed

#### Steps to reproduce the behaviour

This was a fresh sync from an empty datadir.

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd33c86]
goroutine 204971 [running]:
github.com/ledgerwatch/turbo-geth/core.(*accountSet).containsTx(0x0, 0xc65ea8e000, 0xf09f74412efb90e7)
        github.com/ledgerwatch/turbo-geth/core/tx_pool.go:1508 +0x26
github.com/ledgerwatch/turbo-geth/core.(*TxPool).add(0xc000140900, 0xc65ea8e000, 0x0, 0xc6c0dee160, 0x0, 0xc6c0dee140)
        github.com/ledgerwatch/turbo-geth/core/tx_pool.go:612 +0x15f3
github.com/ledgerwatch/turbo-geth/core.(*TxPool).addTxsLocked(0xc000140900, 0xc10aeaa020, 0x2, 0x2, 0xaddfd8399870e200, 0x62253002, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/core/tx_pool.go:883 +0xd2
github.com/ledgerwatch/turbo-geth/core.(*TxPool).addTxs(0xc000140900, 0xc6c0dee020, 0x2, 0x4, 0x3db9ddc7d9950000, 0xc000700400, 0x0, 0x29553ed0135ea34b)
        github.com/ledgerwatch/turbo-geth/core/tx_pool.go:858 +0x370
github.com/ledgerwatch/turbo-geth/core.(*TxPool).AddRemotes(0xc000140900, 0xc6c0dee020, 0x2, 0x4, 0x1392e00, 0xc45397aa71f7b01, 0xc5f0902040)
        github.com/ledgerwatch/turbo-geth/core/tx_pool.go:803 +0x50
github.com/ledgerwatch/turbo-geth/eth/fetcher.(*TxFetcher).Enqueue(0xc000034420, 0xc002749040, 0x40, 0xc6c0dee020, 0x2, 0x4, 0xc00cad3700, 0xc002ddac48, 0x1392e00)
        github.com/ledgerwatch/turbo-geth/eth/fetcher/tx_fetcher.go:278 +0xd7
github.com/ledgerwatch/turbo-geth/eth.(*ethHandler).Handle(0xc000390140, 0xc003634340, 0x161dac0, 0xc6c089e060, 0x96f09b583d87a7ed, 0x7d2390c0bb20)
        github.com/ledgerwatch/turbo-geth/eth/handler_eth.go:92 +0xe5
github.com/ledgerwatch/turbo-geth/eth/protocols/eth.handleTransactions(0x16360e0, 0xc000390140, 0x1620d00, 0xc64f29c000, 0xc003634340, 0xc010f2ae1da76e1c, 0x25246a1b2200)
        github.com/ledgerwatch/turbo-geth/eth/protocols/eth/handlers.go:443 +0x232
github.com/ledgerwatch/turbo-geth/eth/protocols/eth.handleMessage(0x16360e0, 0xc000390140, 0xc003634340, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/protocols/eth/handler.go:238 +0x423
github.com/ledgerwatch/turbo-geth/eth/protocols/eth.Handle(0x16360e0, 0xc000390140, 0xc003634340, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/protocols/eth/handler.go:152 +0x45
github.com/ledgerwatch/turbo-geth/eth/protocols/eth.MakeProtocols.func1.1(0xc003634340, 0x0, 0xc008a55de8)
        github.com/ledgerwatch/turbo-geth/eth/protocols/eth/handler.go:109 +0x3d
github.com/ledgerwatch/turbo-geth/eth.(*handler).runEthPeer(0xc000390140, 0xc003634340, 0xc002ddacc0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/handler.go:311 +0xcf7
github.com/ledgerwatch/turbo-geth/eth.(*ethHandler).RunPeer(0xc000390140, 0xc003634340, 0xc002ddacc0, 0xc000274000, 0x7f24de10f0a0)
        github.com/ledgerwatch/turbo-geth/eth/handler_eth.go:43 +0x3f
github.com/ledgerwatch/turbo-geth/eth/protocols/eth.MakeProtocols.func1(0xc003b110e0, 0x161dcc0, 0xc000274000, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/protocols/eth/handler.go:108 +0x11a
github.com/ledgerwatch/turbo-geth/p2p.(*Peer).startProtocols.func1(0xc003b110e0, 0xc000274000, 0x161dcc0, 0xc000274000)
        github.com/ledgerwatch/turbo-geth/p2p/peer.go:394 +0x98
created by github.com/ledgerwatch/turbo-geth/p2p.(*Peer).startProtocols
        github.com/ledgerwatch/turbo-geth/p2p/peer.go:392 +0x205
````

**Comment by AlexeyAkhunov** [comment]
Thanks for the report! It looks like another thing that got lost during rebase to Geth 1.10.1. Will look at it

**Comment by AskAlexSharov** [comment]
Fixed in https://github.com/ledgerwatch/turbo-geth/pull/1637

**Comment by AskAlexSharov** [comment]
Mergrd. Feel free to test
