### ISSUE TITLE
Panic during block execution at height 9869460

### ISSUE THREAD

**Issue by pipermerriam** [ledgerwatch/turbo-geth#1663]
#### System information

Geth version: 5b87126b4302a2794eca22651b69357122ae960e
OS & Version: Linux
Commit hash : 5b87126b4302a2794eca22651b69357122ae960e

#### Expected behaviour

Blocks to execute

#### Actual behaviour

Client panics and crashes

#### Steps to reproduce the behaviour

This was a fresh sync from an empty database.

#### Backtrace

````
panic: runtime error: index out of range [0] with length 0                                                                                [9/3876]
goroutine 1461 [running]:
github.com/ledgerwatch/turbo-geth/turbo/shards.ReadHeap.Swap(0xc8270ae000, 0x0, 0x50da00, 0x0, 0xffffffffffffffff)
        github.com/ledgerwatch/turbo-geth/turbo/shards/state_cache.go:330 +0x125
container/heap.Pop(0x1841840, 0xc0005aa1e0, 0xc666946de0, 0x0)
        container/heap/heap.go:62 +0x64
github.com/ledgerwatch/turbo-geth/turbo/shards.(*StateCache).setWrite(0xc0005aa160, 0x184f520, 0xc666946de0, 0x183e4c0, 0xc16bf80640, 0x0)
        github.com/ledgerwatch/turbo-geth/turbo/shards/state_cache.go:674 +0x1a9
github.com/ledgerwatch/turbo-geth/turbo/shards.(*StateCache).SetCodeWrite(0xc0005aa160, 0xc2e89fc5c0, 0x14, 0x14, 0x1, 0xc2e3a1d74a, 0x16, 0x16)
        github.com/ledgerwatch/turbo-geth/turbo/shards/state_cache.go:908 +0x1f6
github.com/ledgerwatch/turbo-geth/core/state.(*CachedWriter).UpdateAccountCode(0xc171565520, 0x189db0c75da286a2, 0x954a7f80c2513aa8, 0x6a40270356e61ca4, 0x1, 0xd55739dd39d80cd8, 0xa102a2ad8007b972, 0x94eada7528fa3639, 0xd2f19e1e37636221, 0xc2e3a1d74a, ...)
        github.com/ledgerwatch/turbo-geth/core/state/cached_writer.go:35 +0x157
github.com/ledgerwatch/turbo-geth/core/state.updateAccount(0x183da40, 0xc11e5a5bf0, 0x7de17c23f008, 0xc171565520, 0x189db0c75da286a2, 0x954a7f80c2513aa8, 0x56e61ca4, 0xc11e28fce0, 0x1, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/state/intra_block_state.go:799 +0x28e
github.com/ledgerwatch/turbo-geth/core/state.(*IntraBlockState).CommitBlock(0xc4f50e7900, 0x183da40, 0xc11e5a5bf0, 0x7de17c23f008, 0xc171565520, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/core/state/intra_block_state.go:857 +0x2a7
github.com/ledgerwatch/turbo-geth/core.FinalizeBlockExecution(0x1850520, 0xc000498340, 0xc11d863d40, 0xc11d863680, 0x44, 0x44, 0x2193300, 0x0, 0x0, 0x1849f80, ...)
        github.com/ledgerwatch/turbo-geth/core/blockchain.go:1972 +0x15e
github.com/ledgerwatch/turbo-geth/core.ExecuteBlockEphemerally(0x20425e0, 0xc0004de3a8, 0x182c040, 0xc0004945c0, 0x1850520, 0xc000498340, 0xc048396d80, 0x18412c0, 0xc171565500, 0x1849f80, ...)
        github.com/ledgerwatch/turbo-geth/core/blockchain.go:1950 +0x1114
github.com/ledgerwatch/turbo-geth/eth/stagedsync.executeBlockWithGo(0xc048396d80, 0x18531c0, 0xc0122625c0, 0xc0005aa160, 0x18531c0, 0xc0122625c0, 0x20425e0, 0x182c040, 0xc0004945c0, 0xc0004de3a8, ...)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_execute.go:102 +0x2a7
github.com/ledgerwatch/turbo-geth/eth/stagedsync.SpawnExecuteBlocksStage(0xc013dec060, 0x1853120, 0xc0004292d0, 0x20425e0, 0xc0004945c0, 0xc0004de3a8, 0xc0003ba420, 0x0, 0x1, 0xc0005aa160, ...)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_execute.go:200 +0x109f
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DefaultStages.func5.1(0xc013dec060, 0x181a7e0, 0xc0002edce0, 0x9, 0x1835f00)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagebuilder.go:210 +0x125
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc0002edce0, 0xc0005b0370, 0x1835f00, 0xc0004292d0, 0x1835f00, 0xc0004292d0, 0x8, 0x10)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:270 +0x155
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc0002edce0, 0x7de1d8617ec8, 0xc0004292d0, 0x7de1d8617ec8, 0xc0004292d0, 0xc0004de3

        github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:201 +0x348
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc0004c6200, 0xc000a2a690, 0xb5103c3ac64d3976, 0xaf57af5df8624657, 0x
36, 0xc0002a4d80, 0x16cc978, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:608 +0xe19
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc0004c6200, 0xc0004a0d00, 0x40, 0xb5103c3ac64d3976, 0xaf57af5df862465
xb94f36, 0xc000000001, 0xc0002a4d80, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:450 +0x3a5
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc0004c6200, 0xc0004a0d00, 0x40, 0xb5103c3ac64d3976, 0xaf57af5df862465
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc0004c6200, 0xc0004a0d00, 0x40, 0xb5103c3ac64d3976, 0xaf57af5df8624657, 0x3fa15a272013574f, 0x517701d920567531, 0xb94f36, 0xa9c204fd00000001, 0xc0002a4d80, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:365 +0xa6
github.com/ledgerwatch/turbo-geth/eth.(*handler).doSync(0xc00016a000, 0xc000286680, 0x0, 0xc0004d26e0)
        github.com/ledgerwatch/turbo-geth/eth/sync.go:291 +0xcb
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync.func1(0xc000442930, 0xc000286680)
        github.com/ledgerwatch/turbo-geth/eth/sync.go:284 +0x38
created by github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync
        github.com/ledgerwatch/turbo-geth/eth/sync.go:284 +0x76
````

**Comment by AskAlexSharov** [comment]
Thank you! 
But probably you using --cacheSize flag - which is experimental (and a bit broken now). 
Please use --batchSize instead. 
Fixed by https://github.com/ledgerwatch/turbo-geth/pull/1711
