### ISSUE TITLE
nil pointer in Clique (Görli sync)

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1791]
I get some reports about this kind of error:

#### Backtrace

````

INFO [04-23|16:33:11.468] Timings                                  Headers=62.969322ms    BlockHashes=4.691876ms  Bodies=290.90202ms  Bodies=1.323321ms   Senders=1.447224ms  Execution=8.219033ms   HashState=17.459284ms  IntermediateHashes=8.763542ms   AccountHistoryIndex=3.536657ms   StorageHistoryIndex=11.205682ms  LogIndex=7.073715ms   TxLookup=13.265516ms  TxPool="490.507µs" Finish=4.003865ms
snapshotByHeader 4670469 (epoch 30000, checkpoint interval 10) d1935341e9625624291b6d68542f0853c56d73e99b8ae60d956eb9368ae9edd1 returns nil
ERROR[04-23|16:33:12.003] Ethereum peer removal failed             peer=fe43f085 err="peer not registered"
snapshotByHeader 4670469 (epoch 30000, checkpoint interval 10) d1935341e9625624291b6d68542f0853c56d73e99b8ae60d956eb9368ae9edd1 returns nil
ERROR[04-23|16:33:15.406] Ethereum peer removal failed             peer=f58a097d err="peer not registered"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xed1729]
goroutine 97340 [running]:
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).getAncestors(0xc00018e6e0, 0x183d418, 0xc00045cf30, 0x474406, 0x51060fb53368eef6, 0xa103eb6e54592669, 0xcb3b9137b2eaf5b2, 0x6d08c287db5ab368, 0x245662e9415393d1, 0x53082f54686d1b29, ...)
        github.com/ledgerwatch/turbo-geth/consensus/clique/verifier.go:399 +0xc9
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).VerifyHeaders.func3(0xc00018e6e0, 0x183d418, 0xc00045cf30, 0xc00359e8f0, 0x1, 0x1, 0xc00285f6e0, 0xc0006774a0)
        github.com/ledgerwatch/turbo-geth/consensus/clique/clique.go:379 +0x14b
created by github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).VerifyHeaders
        github.com/ledgerwatch/turbo-geth/consensus/clique/clique.go:378 +0x20a
````

**Comment by brotchie** [comment]
Had a similar crash earlier today, stack trace was slightly different. Syncing on goerli.

```
INFO [04-24|20:01:49.676] [14/14 Finish] Update current block for the RPC API to=4678724
INFO [04-24|20:01:49.676] Memory                                   alloc=36.88MiB sys=142.43MiB
INFO [04-24|20:01:49.676] Timings                                  Headers=568.556902ms   BlockHashes=1.334818ms   Bodies=3m7.430968283s Bodies="484.89µs"     Senders=1.660655ms  Execution=7.003998ms    HashState=2.672654ms   IntermediateHashes=5.385042ms   AccountHistoryIndex=1.004313ms   StorageHistoryIndex=1.460266ms   LogIndex=1.305643ms   TxLookup=1.674496ms   TxPool=2.036814ms  Finish="581.505µs"
INFO [04-24|20:01:49.677] snapshotByHeader returns nil             block=4678725 epoch=30000 checkpoint interval=10 hash=0x5a4812052b6e69643c636240dd7b8de2edc48cfa782ba778d2c79d5699fd1058
INFO [04-24|20:01:49.677] snapshotByHeader returns nil             block=4678725 epoch=30000 checkpoint interval=10 hash=0x968d018f0ba3efe7c8c497e463052aa80b3620f9d0484e12b5dbeb7124e78727
ERROR[04-24|20:01:49.677] Ethereum peer removal failed             peer=2c59d393 err="peer not registered"
ERROR[04-24|20:01:49.677] Ethereum peer removal failed             peer=2c59d393 err="peer not registered"
INFO [04-24|20:01:50.417] [1/14 Headers] Imported new block headers count=12   elapsed=1.061ms     number=4678736 hash="e2375f…5c41e3"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xecfdf7]

goroutine 175070 [running]:
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).snapshotFromAncestors(0xc0004c8210, 0xc001ecce18, 0x55e5916acec7565b, 0x8f1ef4c041cce8fd, 0xb6747a4e5e050768)
	github.com/ledgerwatch/turbo-geth/consensus/clique/verifier.go:225 +0xb7
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).verifyCascadingFieldsByAncestors(0xc0004c8210, 0x183e578, 0xc002f655d8, 0xc0017cbd40, 0xc0009f4180, 0x1, 0x1, 0x7ffa21b5b818, 0xc00297f580)
	github.com/ledgerwatch/turbo-geth/consensus/clique/verifier.go:121 +0xa5
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).verifyHeader(0xc0004c8210, 0x183e578, 0xc002f655d8, 0xc0017cbd40, 0xc00029a168, 0x0, 0x1, 0xcac441340f360f7c, 0xf69e7d5d6b2be4c5)
	github.com/ledgerwatch/turbo-geth/consensus/clique/verifier.go:26 +0xb5
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).VerifyHeaders.func3(0xc0004c8210, 0x183e578, 0xc002f655d8, 0xc00029a168, 0x1, 0x1, 0xc0005ac8a0, 0xc001e921e0)
	github.com/ledgerwatch/turbo-geth/consensus/clique/clique.go:394 +0x2ce
created by github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).VerifyHeaders
	github.com/ledgerwatch/turbo-geth/consensus/clique/clique.go:380 +0x20a
```

**Comment by brotchie** [comment]
FYI, I've continued to sync Goerli from master and no further crashes, thanks for fixing.
