### ISSUE TITLE
eth_getBlockByNumber method handler crashed

### ISSUE THREAD

**Issue by 0xD34D81** [ledgerwatch/turbo-geth#1811]
#### System information

Geth version: `tg version 2021.05.1-alpha`
OS & Version: Linux

#### Expected behaviour

Whenever I receive a new block event, I immediately recover the block content.

#### Actual behaviour

Sometimes the call crashes and is unable to retrieve the data.

#### Steps to reproduce the behaviour

1. Start a `newBlockHeaders` subscription with ethers.js (`provder.on('block', callback)`)
2. Whenever a new block header is received, perform an `eth_getBlockByNumber` rpc call with provided block number

#### Backtrace

````
ERROR[04-26|07:47:42.336] RPC method eth_getBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference                                                                          [23/29]
goroutine 256 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc0063cc030, 0x14, 0xc003589d50)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xbd
panic(0x10358c0, 0x18c75f0)
        runtime/panic.go:965 +0x1b9
github.com/holiman/uint256.(*Int).ToBig(0x0, 0xc005758fc0)
        github.com/holiman/uint256@v1.1.1/conversion.go:32 +0x55
github.com/ledgerwatch/turbo-geth/internal/ethapi.newRPCTransaction(0x12f89c8, 0xc0003c2120, 0x556f4d605c0561d0, 0x87b97361ebf51fc4, 0x9584c2c48eb93653, 0x4fccb14672c2c852, 0xbbe826, 0xd, 0x48019891a7320c70)
        github.com/ledgerwatch/turbo-geth/internal/ethapi/api.go:861 +0x448
github.com/ledgerwatch/turbo-geth/internal/ethapi.newRPCTransactionFromBlockIndex(0xc00476a510, 0xd, 0x20)
        github.com/ledgerwatch/turbo-geth/internal/ethapi/api.go:884 +0xc9
github.com/ledgerwatch/turbo-geth/internal/ethapi.newRPCTransactionFromBlockHash(0xc00476a510, 0x3bffbb54b063b1df, 0x7fa907895e957a3c, 0x3c5dba70a3ed9a8e, 0xa5c305cf25e9f81a, 0xc0063c6a90)
        github.com/ledgerwatch/turbo-geth/internal/ethapi/api.go:911 +0x125
github.com/ledgerwatch/turbo-geth/internal/ethapi.RPCMarshalBlock.func2(0x12f89c8, 0xc0003c2120, 0xfad820, 0xc0063c6a90, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/internal/ethapi/api.go:751 +0x74
github.com/ledgerwatch/turbo-geth/internal/ethapi.RPCMarshalBlock(0xc00476a510, 0x7e002fff0101, 0xb, 0xb, 0x0)
        github.com/ledgerwatch/turbo-geth/internal/ethapi/api.go:758 +0x1eb
github.com/ledgerwatch/turbo-geth/turbo/adapter/ethapi.RPCMarshalBlock(0xc00476a510, 0xc004770101, 0xc0035897c0, 0xf, 0xc004775878, 0x4fccb14672c2c852)
        github.com/ledgerwatch/turbo-geth/turbo/adapter/ethapi/internal.go:35 +0x58
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GetBlockByNumber(0xc0002b44c0, 0x12e8b10, 0xc0003e0c80, 0xbbe826, 0x1, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_block.go:42 +0x329
reflect.Value.call(0xc0032d8580, 0xc0004161f0, 0x13, 0x117e128, 0x4, 0xc005fe4060, 0x4, 0x4, 0xc005fe4090, 0xc0003d8540, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0032d8580, 0xc0004161f0, 0x13, 0xc005fe4060, 0x4, 0x4, 0x0, 0x0, 0xfa5860)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000110c60, 0x12e8b10, 0xc0003e0c80, 0xc0063cc030, 0x14, 0xc0003d8540, 0x2, 0x2, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc00476a1b0, 0x12e8b10, 0xc0003e0c80, 0xc00021e460, 0xc000110c60, 0xc0003d8540, 0x2, 0x2, 0x2)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:399 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc00476a1b0, 0xc00028dc50, 0xc00021e460, 0xc0003faec0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:347 +0x252
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc00476a1b0, 0xc00028dc50, 0xc00021e460, 0x12dd201)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:301 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc00028dc50)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:142 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc00476a1b0, 0xc00476c048)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:229 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:225 +0x66

WARN [04-26|07:47:42.336] Served                                   conn=172.18.0.6:35208 method=eth_getBlockByNumber reqid=76 t=7.247397ms err="method handler crashed"
````

**Comment by AskAlexSharov** [comment]
Fixed by https://github.com/ledgerwatch/turbo-geth/pull/1813
