### ISSUE TITLE
pending tx subscription crashes rpcdaemon

### ISSUE THREAD

**Issue by 0xD34D81** [ledgerwatch/turbo-geth#1821]
#### System information

Geth version: `tg version 2021.05.1-alpha`
OS & Version: Linux

#### Expected behaviour

Pending tx subscription should work

#### Actual behaviour

Attempting to create a new pending tx subscription crashes `rpcdaemon`

#### Steps to reproduce the behaviour

```
mkdir reproduction
cd reproduction
npm install ethers
```

create an `index.js` file with the following content (assuming the rpcdaemon listens on 127.0.0.1:8545 with ws enabled)

```
const ethers = require('ethers');

const provider = new ethers.providers.WebSocketProvider('ws://127.0.0.1:8545');

provider.on('pending', console.log);
```

and run `node index.js`

should make the `rpcdaemon` crash

#### Backtrace

````
panic: assignment to entry in nil map

goroutine 198 [running]:
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/filters.(*Filters).SubscribePendingTxs(0xc00015c7c0, 0xc000401ce0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/filters/filters.go:97 +0xa5
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).NewPendingTransactions.func1(0xc00015c840, 0xc0035702d0, 0xc00353f8f0)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_filters.go:82 +0xae
created by github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).NewPendingTransactions
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_filters.go:79 +0xae
➜  ~ rpcdaemon --datadir /home/mortimr/data/tg --private.api.addr=localhost:9090 --ws --http.addr 172.17.0.1 --http.vhosts "*"
````

**Comment by AskAlexSharov** [comment]
Fixed by https://github.com/ledgerwatch/turbo-geth/pull/1819
thank you
