### ISSUE TITLE
RPC daemon crashing TG

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1876]
#### Backtrace

````
Hashes=109.779654ms AccountHistoryIndex=27.991406ms  StorageHistoryIndex=36.883927ms  LogIndex=24.21022ms   TxLookup=50.902353ms  TxPool=30.846251ms Finish=1.062381ms
INFO [05-04|10:29:06.830] event subscription channel closed with the RPC daemon
INFO [05-04|10:29:06.830] event subscription channel closed with the RPC daemon
fatal error: concurrent map writesINFO [05-04|10:29:15.269] event subscription channel established with the RPC daemon


goroutine 9576472 [running]:
runtime.throw(0x16289ef, 0x15)
        runtime/panic.go:1117 +0x72 fp=0xc031f23a58 sp=0xc031f23a28 pc=0x4705f2
runtime.mapassign_fast64(0x14417c0, 0xc00153c270, 0x3, 0x4)
        runtime/map_fast64.go:101 +0x33e fp=0xc031f23a98 sp=0xc031f23a58 pc=0x44b05e
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*Events).AddHeaderSubscription(...)
        github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/events.go:31
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*EthBackendServer).Subscribe(0xc00153c480, 0xc04ea81ef0, 0x1fc4778, 0xc02b98f730, 0xc00153c480, 0x110000c031f23be8)
        github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/ethbackend.go:55 +0xe6 fp=0xc031f23b00 sp=0xc031f23a98 pc=0xf08926
github.com/ledgerwatch/turbo-geth/gointerfaces/remote._ETHBACKEND_Subscribe_Handler(0x156c620, 0xc00153c480, 0x1fc2358, 0xc013f52300, 0x20, 0x20)
````

**Comment by AskAlexSharov** [comment]
Fixed by: https://github.com/ledgerwatch/turbo-geth/pull/1882

**Comment by AskAlexSharov** [comment]
oh, it's even not "panic" it's "fatal error" - so "grpc recovery interceptor" can't catch it :-)
