### ISSUE TITLE
no-mod-root failing after block 4207077

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#189]
Here is the backtrace:
````
Processed 4207000 blocks
INFO [11-21|01:26:41.324] Database closed                          database=/mnt/disks/nvme/state
INFO [11-21|01:26:41.448] Database closed                          database=/mnt/disks/nvme/geth/chaindata
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/ledgerwatch/turbo-geth/trie.(*HashBuilder).accountLeafHash(0xc19492a000, 0x3b, 0xf, 0xc194115a01, 0x41)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/hashbuilder.go:310 +0x7c7
github.com/ledgerwatch/turbo-geth/trie.GenStructStep(0xc00000000f, 0xc00366dfb0, 0x0, 0xc194115ad0, 0x41, 0xc1, 0xc194115a00, 0x0, 0xc1, 0xdb1b80, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/gen_struct_step.go:121 +0x890
github.com/ledgerwatch/turbo-geth/trie.StreamHash(0xc00366e4b8, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/stream.go:323 +0x19ab
github.com/ledgerwatch/turbo-geth/trie.HashWithModifications(0xc019859e30, 0xc19446a000, 0x8e, 0x100, 0xc04ef7b200, 0x8e, 0x8e, 0xc194452000, 0x73, 0x80, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/stream.go:556 +0x3456
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).CalcTrieRoots(0xc0000ec0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15467d8)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:480 +0x193
main.stateless(0x7fffc0cb368b, 0x1e, 0x7fffc0cb36b5, 0x15, 0x2625a0, 0x1)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/stateless.go:245 +0x200e
main.main()
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/state.go:1677 +0x6e1
````
I verified the state file by using
````
./build/bin/state -action verifySnapshot -chaindata /mnt/disks/nvme/state
````
and got the output:
````
Block number: 0
Block root hash: d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544
mismatching hash: <d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544>  049bac1cf6819b3e074399f6d59602d9bab0c32eaaf06799ab63c97600a7a117 for prefix ,
 resolveHex , resolvePos 0
Trie computation took 16.127296564s
Storage trie computation took 41.287050808s
````
That gave me the root hash `049bac1cf6819b3e074399f6d59602d9bab0c32eaaf06799ab63c97600a7a117` which I used to figure out the block number:
````
./build/bin/hack -action testBlockHashes -chaindata /mnt/disks/nvme/geth/chaindata -blo
ck 4207000 -hash 049bac1cf6819b3e074399f6d59602d9bab0c32eaaf06799ab63c97600a7a117
````
and got the output:
````
===============
Canonical hash for 4207077: 2d2307dc940b3366fe5a9aeccb0c4c09d21ef2ef385e5b4ed8986fcce10c2766
Header.Root: 049bac1cf6819b3e074399f6d59602d9bab0c32eaaf06799ab63c97600a7a117
Header.TxHash: 8493c4fde8c6d6ab37c5c17a30cb1398619688145ad4519b5564e470bc9ada00
Header.UncleHash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
````

This is how I determined the state file corresponds to the state just after `4207077` and I need to re-run the next time with `-block 4207078` to debug

**Comment by AlexeyAkhunov** [comment]
Figured out how to fix it, and it goes ahead. PR incoming soon
