### ISSUE TITLE
State Analytics: client-side error while running stateGrowth

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#241]
Have been running the command
````
./build/bin/state stateGrowth --remote-db-addr localhost:9999
````

for a while, it went through the account records OK, and then started to get some errors while processing storage records (I realised this was before the server processed got killed, most probably because of the memory pressure, since I was running client and server on the same machine):
````
Processed 296800000 storage records
Processed 296900000 storage records
Processed 297000000 storage records
ERROR[12-08|21:14:54.222] could not decode key in response         error="cbor decode error [pos 24791039420]: read tcp 127.0.0.1:44984->127.0.0.1:9999: read: connection 
reset by peer" command=8
ERROR[12-08|21:14:54.274] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
ERROR[12-08|21:14:54.275] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
ERROR[12-08|21:14:54.275] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
ERROR[12-08|21:14:54.275] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
ERROR[12-08|21:14:54.275] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8

````

But it looks like processing still went on with all the errors:
````
ERROR[12-08|21:14:55.210] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
Processed 297100000 storage records
ERROR[12-08|21:14:55.210] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
````

when I sent SIGTERM signal, I got this in the log:
````
ERROR[12-08|21:17:03.583] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
ERROR[12-08|21:17:03.583] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
INFO [12-08|21:17:03.536] Got interrupt, shutting down... 
ERROR[12-08|21:17:03.583] Could not encode command                 error="cbor encode error: write tcp 127.0.0.1:44984->127.0.0.1:9999: write: broken pipe" command=8
panic: can't encode CmdEndTx: {{%!w(string=cbor) %!w(*net.OpError=&{write tcp 0xc00009c210 0xc00009cb10 0xc37b7ea060})}}
goroutine 1 [running]:
github.com/ledgerwatch/turbo-geth/cmd/state/stateless.check(...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/stateless/state.go:44
github.com/ledgerwatch/turbo-geth/cmd/state/stateless.(*Reporter).StateGrowth2(0xc000153ac0, 0xdfd320, 0xc000156380)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/stateless/state.go:274 +0xd7a
github.com/ledgerwatch/turbo-geth/cmd/state/commands.init.2.func1(0xc00019a280, 0xc000153a40, 0x0, 0x2, 0x0, 0x0)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/commands/state_growth.go:29 +0x125
github.com/spf13/cobra.(*Command).execute(0xc00019a280, 0xc000153a00, 0x2, 0x2, 0xc00019a280, 0xc000153a00)
        /home/akhounov/workspace/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x150a840, 0xc000066548, 0xc00014ea60, 0xc000153901)
        /home/akhounov/workspace/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/akhounov/workspace/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/ledgerwatch/turbo-geth/cmd/state/commands.Execute()
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/commands/root.go:40 +0x32
main.main()
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/cmd/state/main.go:29 +0x137
````

**Comment by AskAlexSharov** [comment]
fixed
