### ISSUE TITLE
THIN_HISTORY: Incorrect rewinding

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#293]
I managed to sync to the head of the mainnet. And then I hit the reorg issue:
````
NFO [12-29|02:22:47.180] Imported new chain segment               blocks=1   txs=231   mgas=9.885   elapsed=135.432ms mgasps=72.987  number=9178709 ha
sh=96e228…950b65 batch=1242
INFO [12-29|02:22:47.436] Memory                                   nodes=4999936 alloc=9203434  sys=15762285 numGC=2230
INFO [12-29|02:22:47.436] Database                                 size=504395386880 written=19656705
INFO [12-29|02:22:59.067] Inserting chain                          start=9178710 end=9178710
INFO [12-29|02:22:59.098] Imported new chain segment               blocks=1   txs=62    mgas=2.077   elapsed=30.320ms  mgasps=68.498  number=9178710 ha
sh=a72991…b684c6 batch=247
INFO [12-29|02:22:59.178] Memory                                   nodes=4999960 alloc=9262505  sys=15762285 numGC=2230
INFO [12-29|02:22:59.178] Database                                 size=504395386880 written=5935105
INFO [12-29|02:23:28.069] Inserting chain                          start=9178711 end=9178711
INFO [12-29|02:23:28.194] Imported new chain segment               blocks=1   txs=169   mgas=9.869   elapsed=124.691ms mgasps=79.150  number=9178711 ha
sh=df87f5…e92883 batch=1158
INFO [12-29|02:23:28.424] Memory                                   nodes=4999900 alloc=8825084  sys=15762285 numGC=2231
INFO [12-29|02:23:28.424] Database                                 size=504395386880 written=18243585
INFO [12-29|02:23:32.547] Inserting chain                          start=9178711 end=9178711
WARN [12-29|02:23:32.555] Ignoring the chain segment because of insufficient difficulty external=13472139851710989130122 local=13472139851710989130122
WARN [12-29|02:23:32.555] Saving                                   block=9178711 hash=cb8e9d…0143a4
INFO [12-29|02:23:48.653] Inserting chain                          start=9178712 end=9178712
WARN [12-29|02:23:48.660] Chain segment's parent not on canonical hash, adding to pre-blocks block=9178711 hash=cb8e9d…0143a4
INFO [12-29|02:23:48.661] Rewinding from                           block=9178711 to block=9178710
ERROR[12-29|02:23:48.749] Incorrect rewinding                      root=4344d9a3d7103c23cbc1ee526d63c5198bc6d8a19cbf2f1b37f22c9c022d1a6a expected=c5a0a
b189f77bf3e5735af335157121a78e2a132aadd9ef57bfb37705c178871
INFO [12-29|02:23:58.304] Inserting chain                          start=9178712 end=9178714
WARN [12-29|02:23:58.315] Chain segment's parent not on canonical hash, adding to pre-blocks block=9178711 hash=cb8e9d…0143a4
INFO [12-29|02:23:58.342] Creating IntraBlockState from latest state block=9178711
INFO [12-29|02:31:21.367] Rebuilt top of account trie and verified root hash="<dfd5f763d4fecc6ea988258adfbcc8331ca525765c17aaa45b1d21b19d77af91> "
INFO [12-29|02:31:21.391] Memory after rebuild                     nodes=69905   alloc=191491   sys=15770733 numGC=2601
INFO [12-29|02:31:21.391] Creation complete. 
INFO [12-29|02:31:21.391] Creation complete. 
INFO [12-29|02:31:21.391] Rewinding from                           block=9178711 to block=9178710
ERROR[12-29|02:33:21.734] Incorrect rewinding                      root=4344d9a3d7103c23cbc1ee526d63c5198bc6d8a19cbf2f1b37f22c9c022d1a6a expected=c5a0a
b189f77bf3e5735af335157121a78e2a132aadd9ef57bfb37705c178871

````

**Comment by AlexeyAkhunov** [comment]
It looks like the problem happens when rewinding any contract that has been changed in the block (it should be easy to write test for it). Here is the excerpt from the `diff_9178710.txt` file that I produced by comparing that supposed to be the state at block `9178710` and what we got after the rewinding:
````
full(
0:full(
  0:full(
    0:hash(b8238bf47734b29a3e7b8a37bfb6471ea3bbc6843a8b6ae87f0f1f018efb25d4)
    1:hash(254bfc323ac354c1c25e67567d17ceee417e6e6549a81b0230bbe117518d57a7)
    2:hash(01889a1001a5715011e2aaffb101ba31083a9856c840c5e2692afab0c20f6d7c)
    3:hash(231d4b7f873db8a3649c55fe682938d483edc07f8b7ce0a6b00bea8f74f718f7)
    4:hash(46c3b3dd5ccd5d57b11bf454fefaa28bcd8307c48a110d53b17ba48fa799cf74)
    5:hash(ab37c057b3c6567419788dfe2b77c4438361ef28bb6287fd81595c537a2e2ff7)
    6:hash(d54782dc802affdeaffbbd859d62e2440f3b30b5b85af32bf51b1442ebdba7cc)
    7:hash(b39c65239c743d2edfea49408795af26b739584f682e738ff5eba58dd19d6e5b)
    8:hash(cbbe8833cfc722961fea3abf04870d7a3c652d272dd8637e3b20a798bcefa0b9)
    9:hash(49de3232c966dd8e2ae239081e90f97119994a0a1be1a0b4cb267bca3dd3c672)
    a:hash(672f701047c7bf3850ac32a83cac20af0a144089527507214a5122b263403f1e)
    b:hash(98f69a55de4654dd72c6bb5f616df166b8db62756866f6e83d734562949810bf)
    c:full(
      0:hash(374d9717a8f9bfd42857828f9645debfda095d56d6ec48b31f0cd1d3b3aed064)
      1:hash(66a632410d91b30608f1edab861be08c3a7b1d0e75fe3eb98118c53dfb27d89b)
      2:hash(a14c6dd2ec23778767ce83cf6e5878607d7dec8e63b9faba3eda9cb818ffa0ae)
      3:hash(d3117029346bb7394272e1cea4ed2d03f68c492f74dde7acc8b6dd5ad63334a9)
      4:hash(da1069495f58fc5322452fbc481a1b68b3646e264bb87d4c7c84cfeb1f019335)
      5:hash(45d435e6e545e3173e6ebfebd2a017a161f629a211c082e9e49472bc7fccb40c)
      6:full(
        0:hash(69121935974c67d261c45eb5e5d69d1ffb32d2db14e139e94e186c8a1dc09156)
        1:hash(4141e18ac9e81110c36fb12a6aa57abf87a8aa4d94a54f42afb674bf572c9fd9)
        2:hash(99c165af2eaf26362eaf58b7babf60c5fca4278dc321eb7a3352d8c409dd2cb2)
        3:hash(e845d117943f3e1e42cb04baca4b04b8d402f60e06aee4d90d90bd10cc297818)
        4:hash(226a7f0cded10569176cedfcbec3f1886c71f875a38b4382c674dbd1c9c5cc04)
        5:hash(2efa505aba7fac8da0643ef87a71b44b2e743a5f485ecb374fd15cea018787dd)
        6:hash(d0d799af1cd75621e5abe0129079aff819a32e0852b78224c70d6999d9cda592)
        7:hash(d75e2308a7f63a645e54b8e930a1d0ff447260c6b01d58821e9fabebd9765fd8)
        8:hash(fd85d5cf941f981b73974169f6a1a563b0ef2555c38f1687067ad791a12798b5)
        9:hash(bcd42ea87e799614d65da15341c71f494136ca59438fcb32c0977d0a006acf7b)
        a:hash(b2820694a71eb43b424f54aaab00e142cee745c21fea2ba0559d22e93531c8a0)
        b:full(
          0:hash(e41a4e481e3288f659cf7e67dae72d654403591cfd3e78edddfc8298c743ae33)
          1:hash(09fe13378b94cd9fa294fbfc8749f82a6c28ded578cacdcb1f3197e0583fb649)
          2:hash(a75d5117ca2eec1050c1a35e7bb946c2f6a801ce2a730c1031d4fabdcf8667e1)
          3:hash(bad39b45035a07ffeacd4577a9a9518d04a57f5dea1e6b76580ad8083cf9008d)
          4:hash(a673a0bc474670935786306e78311d73de0419422124a9c762ead8305d41650f)
          5:hash(43bfaa52a305bc4f061f6beb7c67f442f0860d81210d138f41ca5ad38c017a51)
          6:hash(10ae26ad9e3561055f9160b61b03048c70529d0855ed96832b736f05847fa08e)
          7:hash(19f1167a074d3a57a9b0c2f987f90e56192980e7aa524160a5330d7c9b84db45)
          8:hash(619f148c771f0f4b908707c4d7a1ea46ae871d9e74a588e011e759b85ac538cb)
          9:full(
            2:hash(ea9edf3cde65c6ce860fb50c50190c181e41b364c97fc956f8b8d346c2ed8893)
            7:hash(){0b0f0603070a090c080a060108030a0b0f0f0e04040f0f020c020e01040b0904030a0401060c000706010d0302000f0f000a0406060a07020410: f8440180a08f32103bf7e80a9943
6a6ff0c15e9af7d6803c1ebc0c2f8de404b971e22d67fda0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 } /{0b0f0603070a090c080a060108030a0b0f0f0e04040f0f020c
020e01040b0904030a0401060c000706010d0302000f0f000a0406060a07020410: f8440180a08f32103bf7e80a99436a6ff0c15e9af7d6803c1ebc0c2f8de404b971e22d67fda0e570966a31fa5dbb7feb762
59ba3aec50fed190527be28162d65e4169d128a88 } 
            d:hash(a24ad40c921948619f0bed396d4acfeade17f5fe07fea154ad08e8b46a777d13)
            )
          a:hash(50a95700f46c17e3ea3d056ccbfb37686629c1ce90d9d9d21b08d0212bdd87a2)
          b:hash(5da44bc8ccb7146361ff25610a911fed7265aae9efde64bad8fbd49e2d5d07a4)
          c:hash(){030d080208030e0e0504080507000407070409050a050a04010a03000a0904070c0c030d0b06040a0e0f000000080303010f0907080c0e010e0310: f8440180a056e81f171bcc55a6ff
8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 } /{030d080208030e0e0504080507000407070409050a050a0401
0a03000a0904070c0c030d0b06040a0e0f000000080303010f0907080c0e010e0310: f8440180a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7
db2dcc703c0e500b653ca82273b7bfad8045d85a470 } 
          d:hash(3a92f769d724d6b5c09ffcb7920b2e704b9432460bf98fcfd8cff643da7770c0)
          e:hash(4505d2a6eecbbf7ac149cfe86fd19c4c3720687fa1639c34daf703c699384ef9)
          f:hash(3981d515632eab71f0a177c2b2af38ba4be808cc1c416a5cecada05e3cba69ab)
          )
        c:hash(e7b8b52986c1f80a039858c3597a78e8faac8ad17ebdb8ecb59b1cf589217053)
        d:hash(a7383db61d5fbe4a1f05719cdd4d7c6a6372a75b63e6c8bf3c3672d31c61168e)
        e:hash(e909b5f996d1d0a011a8d9d0e41f526da244b1ca6597a3b6057cf93f4cc142cb)
        f:hash(012f52bcf314ca6a2e7388b659dd2b5cd3e1751e3e6b3d751ce185585940da39)
        )
      7:hash(009060686422f04d09a06a02f62503d4ab95772bd4f03df4e6329840eba722f7)
      8:hash(807313e8c5c15852b66f9e04cfc0c2bf9030ad376393b1a93d7e332a578fb20c)
      9:hash(5d4823b7a81ce102d4ca9b95c27acb7cc45f4cf6f97d78208fa4db9c77a455bc)
      a:hash(1bf3e49f864d7553b1e2801584486248d7d38adb9666a81e3cace73762914f1d)
      b:hash(660e5a35b76392f58438f1b71c5876c06ba6df1d16a48caac84e5d989f18d837)
      c:hash(799743222019e1e4f73d8c4d1f4489960cce07f63cb25f62f9c506d84bc28ad8)
      d:hash(cbe05908ee1fc5eb818169b9cf9f03931e2b9c3012cf442c545e0f29ee72c3d8)
      e:hash(d507ecb2f7e4862a8a6e4d052d3bea1cb9b379300f4f3d82c5dafcade756d24a)
      f:hash(9031ed1472ab9b54fed4e8320fc0e6f08cdd21d6259102b236c82f5cd86df8e3)
      )
    d:hash(ac8bf230059597077e52ce03e12e8ddff7ce621b8acc2aee023a70dc4b594949)
    e:hash(e81eda405d9ea9570a94b0d2bbf5f412ff9c4b4541ad72d4197e2ddb14cb04fe)
    f:hash(13bd3454c9f58917816ab6b58298e729eeac52596654950f10645411d54855fe)
    )
  1:hash(6a2ac2594b15cfeb08f606de98138191fb8183e125fd021f596ca5bb03ac5ac1)
  2:hash(6bb4a075c1d8f781dd54cad3f76d769d9413486e0fcb970b37d62087fb7f9eee)
````

The interesting bit is here:
````
7:hash(){0b0f0603070a090c080a060108030a0b0f0f0e04040f0f020c020e01040b0904030a0401060c000706010d0302000f0f000a0406060a07020410: f8440180a08f32103bf7e80a9943
6a6ff0c15e9af7d6803c1ebc0c2f8de404b971e22d67fda0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 } /{0b0f0603070a090c080a060108030a0b0f0f0e04040f0f020c
020e01040b0904030a0401060c000706010d0302000f0f000a0406060a07020410: f8440180a08f32103bf7e80a99436a6ff0c15e9af7d6803c1ebc0c2f8de404b971e22d67fda0e570966a31fa5dbb7feb76259ba3aec50fed190527be28162d65e4169d128a88 } 
````

The wrong RLP representation of this account is f8440180a08f32103bf7e80a9943
6a6ff0c15e9af7d6803c1ebc0c2f8de404b971e22d67fda0**c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470** (the hash of empty code is in bold), whereas the correct representation is this: f8440180a08f32103bf7e80a99436a6ff0c15e9af7d6803c1ebc0c2f8de404b971e22d67fda0**e570966a31fa5dbb7feb76259ba3aec50fed190527be28162d65e4169d128a88**

So during the unwind, code hashes of contracts are being wiped out, it seems

**Comment by AlexeyAkhunov** [comment]
Next instance of incorrect rewinding:
````
INFO [12-31|05:44:22.002] Imported new chain segment               blocks=1  txs=180  mgas=9.978   elapsed=146.142ms mgasps=68.277  number=9189449 hash=c2d927…dcae8a b
atch=1248
INFO [12-31|05:44:22.210] Memory                                   nodes=2375651 alloc=4317685 sys=8661032 numGC=1134
INFO [12-31|05:44:22.211] Database                                 size=505383419904 written=19378177
INFO [12-31|05:44:28.304] Inserting chain                          start=9189450 end=9189450
INFO [12-31|05:44:28.492] Imported new chain segment               blocks=1  txs=197  mgas=9.969   elapsed=187.834ms mgasps=53.075  number=9189450 hash=0028d8…d7f281 b
atch=1232
INFO [12-31|05:44:28.701] Memory                                   nodes=2375877 alloc=4452958 sys=8661032 numGC=1134
INFO [12-31|05:44:28.701] Database                                 size=505383419904 written=19648513
INFO [12-31|05:44:31.661] Inserting chain                          start=9189450 end=9189450
WARN [12-31|05:44:31.666] Ignoring the chain segment because of insufficient difficulty external=13499563796368075965174 local=13499563796368075965174
WARN [12-31|05:44:31.666] Saving                                   block=9189450 hash=2f7354…1ca889
INFO [12-31|05:44:37.601] Inserting chain                          start=9189451 end=9189451
WARN [12-31|05:44:37.610] Chain segment's parent not on canonical hash, adding to pre-blocks block=9189450 hash=2f7354…1ca889
INFO [12-31|05:44:37.612] Rewinding from                           block=9189450 to block=9189449
WARN [12-31|05:44:37.659] Generating deep snapshot of the wrong tries... file=root_9189449.txt
ERROR[12-31|05:45:18.539] Incorrect rewinding                      root=b1e14963c998099ea337384ae9c94ce4105a1330293122d30ec530e73862c0c6 expected=4b9dbcb63021221da74d8
399c163db5d4d9ba03dc5262cfdbde2c5051009a764
INFO 
````

**Comment by AlexeyAkhunov** [comment]
the next instance is a bit more interesting
it is with this contract: https://etherscan.io/address/0xd892417556ae4a316b2064eb7b6acb7d09a9f30b
The transaction that deployed it first got into a block 9189450, then got reverted by the reorg, and then got re-done in block 9189455

**Comment by AlexeyAkhunov** [comment]
the function CreateAccount in the InterBlockState can be called in 2 different contexts

1) simply sending ETH to an account. Called from core/vm/evm/go:226
2) creating contracts. Called from core/vm/evm.go:405

but we always do newObj.created = true
which means that all incarnations are now 1, for all accounts
not just for contracts

**Comment by AlexeyAkhunov** [comment]
and now the sync blew up:
````
INFO [01-04|13:53:18.928] Memory                                   nodes=4999937 alloc=12155554 sys=24220025 numGC=24766
INFO [01-04|13:53:18.928] Database                                 size=161037811712 written=740528129
INFO [01-04|13:53:19.029] Imported new chain segment               blocks=1    txs=245   mgas=7.982    elapsed=14.950s   mgasps=0.534   number=5543933 hash=4fc1ba…ae6b
15 batch=963    age=1y8mo1w
Key: 050a000e0b090b090e0b080c020d040a0d070a02030f0a0904020704040005010a0701070500070c0403020f040b02080c040a0e07030a0c040e060006010c030209000d0e0c0d090504080b06020a080d
06000304050a0908080308060f0c08040b0a060b0c09050408040000080f060306020f09030106000e0f030e05060310, Pos: 64
panic: trie.hashNode: invalid node: <4b13057b5a6042f32427fa9f4a0ce2eab139009a3a56996b2924dd7d2a2c3529> 
goroutine 3592105 [running]:
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000ba4360, 0x14a05e0, 0xc1db1deb00, 0xc4f6891170, 0x81, 0x81, 0x40, 0x14a0620, 0xc07feea220, 0x421601, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:513 +0x17ff
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000ba4360, 0x149ffa0, 0xc01bfbcd20, 0xc4f6891170, 0x81, 0x81, 0x40, 0x14a0620, 0xc07feea220, 0x4216c9, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:395 +0x1258
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000ba4360, 0x14a0060, 0xc14f984840, 0xc4f6891170, 0x81, 0x81, 0x8, 0x14a0620, 0xc07feea220, 0x4216c9, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:406 +0x21f
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000ba4360, 0x14a0020, 0xc2e760a280, 0xc4f6891170, 0x81, 0x81, 0x7, 0x14a0620, 0xc07feea220, 0x421601, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:503 +0x1162
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000ba4360, 0x14a0020, 0xc3000d2dc0, 0xc4f6891170, 0x81, 0x81, 0x6, 0x14a0620, 0xc07feea220, 0x4216c9, ...)
        /home/akhounov/workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:503 +0x1162
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000ba4360, 0x14a0020, 0xc36587e500, 0xc4f6891170, 0x81, 0x81, 0x5, 0x14a0620, 0xc07feea220, 0xb917016229a4942,
 ...)

````
