### ISSUE TITLE
Fix concurrent map writes error

### ISSUE THREAD

**Issue by JekaMas** [ledgerwatch/turbo-geth#35]
```

goroutine 48 [running]:
runtime.throw(0x72f8b2, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00011a758 sp=0xc00011a728 pc=0x42f862
runtime.mapassign_fast64(0x6cffe0, 0xc000013050, 0x0, 0x5dfd9e)
	/usr/local/go/src/runtime/map_fast64.go:101 +0x35f fp=0xc00011a798 sp=0xc00011a758 pc=0x4135cf
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).leftGeneration(...)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:686
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).leftGeneration-fm(0x0)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:684 +0x49 fp=0xc00011a7c8 sp=0xc00011a798 pc=0x6747d9
github.com/ledgerwatch/turbo-geth/trie.(*duoNode).updateT(0xc0005269c0, 0x1, 0xc0005120d0, 0xc0005120e0)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/trie/node.go:334 +0x48 fp=0xc00011a7e0 sp=0xc00011a7c8 pc=0x5dfc68
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000108100, 0x7a8d00, 0xc0005269c0, 0xc00082acd0, 0x41, 0x41, 0x2, 0x7a8f40, 0xc000820c20, 0xc00011ae90, ...)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:1227 +0xa43 fp=0xc00011a9e8 sp=0xc00011a7e0 pc=0x5fb103
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000108100, 0x7a8d60, 0xc0005d6c60, 0xc00082acd0, 0x41, 0x41, 0x1, 0x7a8f40, 0xc000820c20, 0xc00011ae90, ...)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:1329 +0x633 fp=0xc00011abf0 sp=0xc00011a9e8 pc=0x5facf3
github.com/ledgerwatch/turbo-geth/trie.(*Trie).insert(0xc000108100, 0x7a8d60, 0xc000511760, 0xc00082acd0, 0x41, 0x41, 0x0, 0x7a8f40, 0xc000820c20, 0xc00011ae90, ...)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:1329 +0x633 fp=0xc00011adf8 sp=0xc00011abf0 pc=0x5facf3
github.com/ledgerwatch/turbo-geth/trie.(*Trie).Update(0xc000108100, 0xc00011b200, 0x20, 0x20, 0xc00082ac80, 0x48, 0x48, 0x1)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/trie/trie.go:808 +0x178 fp=0xc00011af30 sp=0xc00011adf8 pc=0x5f7c28
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).computeTrieRoots(0xc000718c60, 0xc000501901, 0x0, 0x3e, 0x8060104, 0x3e, 0xffffffffffffffff)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:498 +0x1a57 fp=0xc000131c10 sp=0xc00011af30 pc=0x656977
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).ComputeTrieRoots(0xc000718c60, 0xc000010201, 0x7a7e80, 0xc000010200, 0x0, 0x0)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:286 +0x34 fp=0xc000131c58 sp=0xc000131c10 pc=0x654b84
github.com/ledgerwatch/turbo-geth/core/state.TestCopy(0xc00010a300)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/statedb_test.go:190 +0x98f fp=0xc000131fa8 sp=0xc000131c58 pc=0x66c71f
testing.tRunner(0xc00010a300, 0x73aec0)
	/usr/local/go/src/testing/testing.go:865 +0xc0 fp=0xc000131fd0 sp=0xc000131fa8 pc=0x4e2250
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000131fd8 sp=0xc000131fd0 pc=0x45da11
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00010a300, 0x72bbd6, 0x8, 0x73aec0, 0x479101)
	/usr/local/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc00010a200)
	/usr/local/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc00010a200, 0xc0000e1e30)
	/usr/local/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc00000f120, 0xbad040, 0xc, 0xc, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc000108180, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:64 +0x13e

goroutine 49 [runnable]:
github.com/ledgerwatch/turbo-geth/rlp.(*encbuf).encodeString(0xc00082c000, 0xc0004a867e, 0x2, 0x2)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:201 +0x1ba
github.com/ledgerwatch/turbo-geth/rlp.writeBigInt(0xc00038c7c0, 0xc00082c000, 0x196, 0x40e801)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:435 +0x199
github.com/ledgerwatch/turbo-geth/rlp.writeBigIntPtr(0x728320, 0xc000297e20, 0x196, 0xc00082c000, 0x728320, 0xc000297e20)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:421 +0x10d
github.com/ledgerwatch/turbo-geth/rlp.makeStructWriter.func1(0x6fc7c0, 0xc000297e18, 0x199, 0xc00082c000, 0xc000297e18, 0x199)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:535 +0x149
github.com/ledgerwatch/turbo-geth/rlp.makePtrWriter.func4(0x6ab120, 0xc000297e18, 0x16, 0xc00082c000, 0x0, 0x0)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:578 +0xb1
github.com/ledgerwatch/turbo-geth/rlp.(*encbuf).encode(0xc00082c000, 0x6ab120, 0xc000297e18, 0x706b00, 0xc00082c000)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:187 +0x135
github.com/ledgerwatch/turbo-geth/rlp.EncodeToBytes(0x6ab120, 0xc000297e18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/rlp/encode.go:101 +0xe4
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).computeTrieRoots(0xc000184000, 0xc0004f2001, 0x0, 0x13, 0x7060107, 0x13, 0xffffffffffffffff)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:494 +0x19ee
github.com/ledgerwatch/turbo-geth/core/state.(*TrieDbState).ComputeTrieRoots(0xc000184000, 0xc000398001, 0x7a7e80, 0xc000398000, 0x0, 0x0)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/database.go:286 +0x34
github.com/ledgerwatch/turbo-geth/core/state.TestCopy.func1(0xc000506000, 0xc000184000, 0xc0003f6120)
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/statedb_test.go:184 +0x7e
created by github.com/ledgerwatch/turbo-geth/core/state.TestCopy
	/go/src/github.com/ledgerwatch/turbo-geth/build/_workspace/src/github.com/ledgerwatch/turbo-geth/core/state/statedb_test.go:182 +0x929
```

**Comment by AlexeyAkhunov** [comment]
Should be disabled by this: https://github.com/ledgerwatch/turbo-geth/pull/36
