### ISSUE TITLE
Fatal error: concurrent map writes (in pruning?)

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/turbo-geth#431]
Happened on my node in cloud after sync

andrey_ashikhmin@issue-340:~/turbo-geth$ git show --oneline -s
b490192e6 (HEAD -> master, origin/master, origin/HEAD) Use KV Abstraction in RestAPI  (#400)

-----------------------------------------------------------------------------------------

INFO [04-06|07:37:00.218] Inserting chain                          start=9817211 end=9817211 current=9817210 currentHeader=9817210 callers="[github.com/ledgerwatch/turbo-geth/core.(*BlockChain).insertChain github.com/ledgerwatch/turbo-geth/core.(*BlockChain).InsertChain github.com/ledgerwatch/turbo-geth/eth.initPm.func3 github.com/ledgerwatch/turbo-geth/eth/fetcher.(*BlockFetcher).insert github.com/ledgerwatch/turbo-geth/eth/fetcher.(*BlockFetcher).loop runtime.goexit]"
fatal error: concurrent map writes

goroutine 99 [running]:
runtime.throw(0x1312168, 0x15)
	/snap/go/5569/src/runtime/panic.go:1114 +0x72 fp=0xc13c650068 sp=0xc13c650038 pc=0x459012
runtime.mapassign_faststr(0x117a340, 0xc0001a79e0, 0xc12261eae9, 0x5, 0xc278c95510)
	/snap/go/5569/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc13c6500d0 sp=0xc13c650068 pc=0x437a37
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).Touch(0xc00047ebc0, 0xc122e439a0, 0x5, 0x41, 0x0)
	/home/andrey_ashikhmin/turbo-geth/trie/trie_pruning.go:146 +0x1b5 fp=0xc13c650150 sp=0xc13c6500d0 pc=0x9ebae5
github.com/ledgerwatch/turbo-geth/trie.(*TriePruning).Touch-fm(0xc122e439a0, 0x5, 0x41, 0x95cc00)
	/home/andrey_ashikhmin/turbo-geth/trie/trie_pruning.go:133 +0x51 fp=0xc13c650188 sp=0xc13c650150 pc=0xa68e31
github.com/ledgerwatch/turbo-geth/trie.(*Trie).getAccount(0xc0001a79b0, 0x15cb0e0, 0xc255451540, 0xc122e439a0, 0x41, 0x41, 0x5, 0xc12261ead9, 0xc12261ead6)

**Comment by yperbasis** [comment]
[out.log](https://github.com/ledgerwatch/turbo-geth/files/4438042/out.log)

**Comment by yperbasis** [comment]
Probably fixed by PR #412.
