### ISSUE TITLE
go test ./eth/downloader frequently times out

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#633]
Here is the possible reason:
````
goroutine 21 [running]:
runtime.heapBitsSetType(0xc003d9cf40, 0x20, 0x20, 0x48f88e0)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/mbitmap.go:1140 +0x1b2 fp=0xc00ff3f0c8 sp=0xc00ff3eff0 pc=0x4017f72
runtime.mallocgc(0x20, 0x48f88e0, 0xc0042e9001, 0x14)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/malloc.go:1052 +0x53e fp=0xc00ff3f168 sp=0xc00ff3f0c8 pc=0x400e57e
runtime.growslice(0x48f88e0, 0x5050e90, 0x0, 0x0, 0x1, 0xc00ff3f238, 0xc0042e1450, 0xc0042e8fc0)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/slice.go:181 +0x1e2 fp=0xc00ff3f1d0 sp=0xc00ff3f168 pc=0x4047722
github.com/ledgerwatch/bolt.(*Cursor).search(0xc00ff3f388, 0x4fc1af4, 0x6, 0x6, 0x14)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/cursor.go:470 +0x29a fp=0xc00ff3f280 sp=0xc00ff3f1d0 pc=0x4493dba
github.com/ledgerwatch/bolt.(*Cursor).seek(0xc00ff3f388, 0x4fc1af4, 0x6, 0x6, 0x5052460, 0xc0064578a0, 0xc003d9cf20, 0xc0042e49b0, 0x5, 0xc00710bcf0, ...)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/cursor.go:260 +0x8b fp=0xc00ff3f300 sp=0xc00ff3f280 pc=0x449276b
github.com/ledgerwatch/bolt.(*Bucket).Bucket(0xc0042dd2d8, 0x4fc1af4, 0x6, 0x6, 0x1)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/bucket.go:118 +0xf4 fp=0xc00ff3f3c0 sp=0xc00ff3f300 pc=0x448c064
github.com/ledgerwatch/bolt.(*Tx).Bucket(...)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/tx.go:103
github.com/ledgerwatch/bolt.(*Tx).commitDBWriteStats(0xc0042dd2c0, 0x0, 0x0)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/tx.go:304 +0x94 fp=0xc00ff3f4e8 sp=0xc00ff3f3c0 pc=0x44a47f4
github.com/ledgerwatch/bolt.(*Tx).Commit(0xc0042dd2c0, 0x0, 0x0)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/tx.go:152 +0x61 fp=0xc00ff3f608 sp=0xc00ff3f4e8 pc=0x44a3ac1
github.com/ledgerwatch/bolt.(*DB).Update(0xc00710bb00, 0xc00ff3f6b0, 0x0, 0x0)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/db.go:771 +0x106 fp=0xc00ff3f690 sp=0xc00ff3f608 pc=0x4497d96
github.com/ledgerwatch/turbo-geth/ethdb.(*BoltKV).Update(0xc004979a40, 0x4ae2c00, 0xc0000b4008, 0xc0042e4960, 0x486b9c0, 0x4873b01)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/ethdb/kv_bolt.go:162 +0xa9 fp=0xc00ff3f6d8 sp=0xc00ff3f690 pc=0x4588b49
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Put(0xc00795d7a0, 0x4fc1a30, 0x3, 0x3, 0xc006457890, 0x1, 0x1, 0xc006457868, 0x8, 0x8, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:46 +0xfa fp=0xc00ff3f720 sp=0xc00ff3f6d8 pc=0x459156a
github.com/ledgerwatch/turbo-geth/eth/stagedsync/stages.SaveStageProgress(0xa115a98, 0xc00795d7a0, 0xc00795d705, 0x0, 0xc00795d7a0, 0x2)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stages/stages.go:59 +0xe2 fp=0xc00ff3f7a8 sp=0xc00ff3f720 pc=0x467a8d2
github.com/ledgerwatch/turbo-geth/eth/stagedsync.SpawnIntermediateHashesStage(0xc003d9cca0, 0x4aefce0, 0xc00795d7a0, 0x0, 0x0, 0xc0003a6660, 0x4f75a90, 0x4fcf700)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_interhashes.go:18 +0x1d9 fp=0xc00ff3f828 sp=0xc00ff3f7a8 pc=0x469e799
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DoStagedSyncWithFetchers.func6(0xc003d9cca0, 0xc0042acc80, 0x4b)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagedsync.go:66 +0x58 fp=0xc00ff3f878 sp=0xc00ff3f828 pc=0x46a2988
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DoStagedSyncWithFetchers(0x4adaa40, 0xc00495cb60, 0xa97b758, 0xc004934780, 0x4aefce0, 0xc00795d7a0, 0x499c357, 0x4, 0xa80ff00, 0x0, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagedsync.go:117 +0xc1d fp=0xc00ff3fa10 sp=0xc00ff3f878 pc=0x46a0c9d
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc00495cb60, 0xc007abc870, 0x9cf57e3a075ad710, 0x2c29c73a0bd5c905, 0x93d90e0c25d797aa, 0x90f5c870e0ef3c29, 0xc008819ec0, 0x4ae2e00, 0xc001182ac0, 0x0, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:548 +0xd48 fp=0xc00ff3fd20 sp=0xc00ff3fa10 pc=0x46b8478
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc00495cb60, 0x499c357, 0x4, 0x9cf57e3a075ad710, 0x2c29c73a0bd5c905, 0x93d90e0c25d797aa, 0x90f5c870e0ef3c29, 0xc008819ec0, 0x3, 0x4ae2e00, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:437 +0x3e4 fp=0xc00ff3fe48 sp=0xc00ff3fd20 pc=0x46b7554
github.com/ledgerwatch/turbo-geth/eth/downloader.(*stagedSyncTester).sync(0xc004934780, 0x499c357, 0x4, 0xc008819ec0, 0xc0000ae0c0, 0x0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_stagedsync_test.go:268 +0x1a1 fp=0xc00ff3ff10 sp=0xc00ff3fe48 pc=0x46d1721
github.com/ledgerwatch/turbo-geth/eth/downloader.TestUnwind(0xc004837300)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_stagedsync_test.go:330 +0xe6 fp=0xc00ff3ff70 sp=0xc00ff3ff10 pc=0x46d2236

````

**Comment by AlexeyAkhunov** [comment]
Here is another try:
````
goroutine 51 [runnable]:
sync.(*RWMutex).Unlock(0xc00117a1f0)
	/usr/local/Cellar/go/1.13/libexec/src/sync/rwmutex.go:118 +0xd2
github.com/ledgerwatch/bolt.(*DB).addTxWriteStats(0xc00117a000, 0xc003881d10)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/db.go:1120 +0x39f
github.com/ledgerwatch/bolt.(*Tx).commitDBWriteStats(0xc0038d8780, 0x0, 0x0)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/tx.go:303 +0x5b
github.com/ledgerwatch/bolt.(*Tx).Commit(0xc0038d8780, 0x0, 0x0)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/tx.go:152 +0x61
github.com/ledgerwatch/bolt.(*DB).Update(0xc00117a000, 0xc00fe9d6b0, 0x0, 0x0)
	/Users/alexeyakhunov/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.6-0.20200605053542-69293d8f1d33/db.go:771 +0x106
github.com/ledgerwatch/turbo-geth/ethdb.(*BoltKV).Update(0xc009a2d470, 0x4ae2c00, 0xc0000b6008, 0xc003811a90, 0x486b9c0, 0x4873b01)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/ethdb/kv_bolt.go:162 +0xa9
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Put(0xc008b3bc40, 0x4fc1a30, 0x3, 0x3, 0xc0080e9898, 0x1, 0x1, 0xc0080e9890, 0x8, 0x8, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:46 +0xfa
github.com/ledgerwatch/turbo-geth/eth/stagedsync/stages.SaveStageProgress(0x7e03178, 0xc008b3bc40, 0xc008b3bc05, 0x0, 0xc008b3bc40, 0x2)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stages/stages.go:59 +0xe2
github.com/ledgerwatch/turbo-geth/eth/stagedsync.SpawnIntermediateHashesStage(0xc008877120, 0x4aefce0, 0xc008b3bc40, 0x0, 0x0, 0xc0000c6480, 0x4f75a90, 0x4fcf700)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_interhashes.go:18 +0x1d9
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DoStagedSyncWithFetchers.func6(0xc008877120, 0xc00382b450, 0x4b)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagedsync.go:66 +0x58
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DoStagedSyncWithFetchers(0x4adaa40, 0xc0000bad00, 0x8a7fce0, 0xc00723e050, 0x4aefce0, 0xc008b3bc40, 0x499c357, 0x4, 0x7afff00, 0x0, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagedsync.go:117 +0xc1d
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc0000bad00, 0xc0003dd4a0, 0x9cf57e3a075ad710, 0x2c29c73a0bd5c905, 0x93d90e0c25d797aa, 0x90f5c870e0ef3c29, 0xc008938f40, 0x4ae2e00, 0xc0078ca2a0, 0x0, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:548 +0xd48
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc0000bad00, 0x499c357, 0x4, 0x9cf57e3a075ad710, 0x2c29c73a0bd5c905, 0x93d90e0c25d797aa, 0x90f5c870e0ef3c29, 0xc008938f40, 0x3, 0x4ae2e00, ...)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:437 +0x3e4
github.com/ledgerwatch/turbo-geth/eth/downloader.(*stagedSyncTester).sync(0xc00723e050, 0x499c357, 0x4, 0xc008938f40, 0xc0000aa1e0, 0x0)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_stagedsync_test.go:268 +0x1a1
github.com/ledgerwatch/turbo-geth/eth/downloader.TestUnwind(0xc000408200)
	/Users/alexeyakhunov/workspace/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_stagedsync_test.go:330 +0xe6
testing.tRunner(0xc000408200, 0x49d18c8)
	/usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:960 +0x350
````
