### ISSUE TITLE
Out of memory while cycling through stages (after full sync)

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#713]
````
INFO [07-05|07:14:25.561] Sync stage 7/9. Generating account history index... DONE! 
INFO [07-05|07:14:25.562] Sync stage 8/9. Generating storage history index... 
INFO [07-05|07:14:25.562] Index generation started                 from=10397926 to=10397931 csbucket=PLAIN-SCS
INFO [07-05|07:14:25.567] Extraction finished                      it took=4.014238ms
INFO [07-05|07:14:26.029] Committed batch                          bucket=hST          size=535.99KiB current key=final       alloc=140.86MiB  sys=4.67GiB   numGC=59606
INFO [07-05|07:14:26.035] Collection finished                      it took=467.684919ms
INFO [07-05|07:14:26.035] Index generation successfully finished   csbucket=PLAIN-SCS it took=473.245932ms
INFO [07-05|07:14:26.038] Sync stage 8/9. Generating storage history index... DONE! 
INFO [07-05|07:14:26.040] Sync stage 9/9. Generating tx lookup index... 
INFO [07-05|07:14:26.056] Extraction finished                      it took=14.066078ms
INFO [07-05|07:14:26.383] Committed batch                          bucket=l            size=41.74KiB  current key=final       alloc=143.19MiB  sys=4.67GiB   numGC=59606
INFO [07-05|07:14:26.383] Collection finished                      it took=327.097297ms
INFO [07-05|07:14:26.384] Sync stage 9/9. Generating tx lookup index... DONE! 
INFO [07-05|07:14:26.694] Staged sync finished 
INFO [07-05|07:14:26.694] Sync stage 1/9. Downloading headers... 
INFO [07-05|07:14:30.270] Imported new block headers               count=6    elapsed=3.109s      number=10397937 hash="d78733…479483" age=16m14s
INFO [07-05|07:14:30.285] Sync stage 1/9. Downloading headers... DONE! 
INFO [07-05|07:14:30.285] Sync stage 2/9. Downloading block bodies... 
INFO [07-05|07:14:30.840] Imported new chain segment               blocks=6    txs=563    mgas=0.000 elapsed=2.473ms     mgasps=0.000 number=10397937 hash="d78733…479483" batch=116.75KiB age=16m14s
INFO [07-05|07:14:31.006] Database                                 size=0.00B     written=0
INFO [07-05|07:14:31.008] Sync stage 2/9. Downloading block bodies... DONE! 
INFO [07-05|07:14:31.008] Sync stage 2/9. Downloading block bodies... 
INFO [07-05|07:14:31.008] Sync stage 2/9. Downloading block bodies... DONE! 
INFO [07-05|07:14:31.008] Sync stage 3/9. Recovering senders from tx signatures... 
INFO [07-05|07:14:31.008] Sync (Senders): Reading canonical hashes complete hashes=6
INFO [07-05|07:14:31.008] Sync (Senders): Started recoverer goroutines numOfGoroutines=8
INFO [07-05|07:14:31.040] Committed batch                          bucket=txSenders    size=11.42KiB  current key=final       alloc=134.40MiB  sys=4.67GiB   numGC=59607
INFO [07-05|07:14:31.042] Sync stage 3/9. Recovering senders from tx signatures... DONE! 
INFO [07-05|07:14:31.042] Sync stage 4/9. Executing blocks w/o hash checks...
INFO [07-05|07:14:31.043] Attempting to start execution from       block=10397932
panic: cannot allocate 67108864 bytes via mmap: cannot allocate memory

goroutine 512197 [running]:
github.com/VictoriaMetrics/fastcache.getChunk(0xc001485b50, 0xc000479080, 0x16e6de0)
	/home/alexey/go/pkg/mod/github.com/!victoria!metrics/fastcache@v1.5.7/malloc_mmap.go:26 +0x36c
github.com/VictoriaMetrics/fastcache.(*bucket).Set(0xc001485b50, 0xc002030588, 0x14, 0x14, 0xc00203053c, 0x4, 0x4, 0x4547ba556f437163)
	/home/alexey/go/pkg/mod/github.com/!victoria!metrics/fastcache@v1.5.7/fastcache.go:348 +0x44a
github.com/VictoriaMetrics/fastcache.(*Cache).Set(0xc00147c000, 0xc002030588, 0x14, 0x14, 0xc00203053c, 0x4, 0x4)
	/home/alexey/go/pkg/mod/github.com/!victoria!metrics/fastcache@v1.5.7/fastcache.go:148 +0xad
github.com/ledgerwatch/turbo-geth/core/state.(*PlainStateReader).ReadAccountCode(0xc02dee9950, 0x457481cd4b2d7b58, 0x1895ea65e619c99a, 0x1a2ac02749a00580, 0x19a6aadc2222282, 0x6dbe5df0ab981c02, 0x76f96e7535005419, 0xc0d041ed97, 0xb352577f, 0x14, ...)
	/home/alexey/turbo-geth/core/state/plain_state_reader.go:105 +0x1a8
github.com/ledgerwatch/turbo-geth/core/state.(*stateObject).Code(0xc002206840, 0x457481cd4b2d7b58, 0x1895ea65e619c99a, 0x49a00580)
	/home/alexey/turbo-geth/core/state/state_object.go:324 +0x164
github.com/ledgerwatch/turbo-geth/core/state.(*IntraBlockState).GetCode(0xc00018ac00, 0x457481cd4b2d7b58, 0x1895ea65e619c99a, 0xc049a00580, 0x0, 0x0, 0x0)
	/home/alexey/turbo-geth/core/state/intra_block_state.go:326 +0x1f4
github.com/ledgerwatch/turbo-geth/core/vm.(*EVM).Call(0xc002206580, 0x16c2980, 0xc006115a20, 0x457481cd4b2d7b58, 0x1895ea65e619c99a, 0xc049a00580, 0xc00165a000, 0x104, 0x104, 0x45842, ...)
	/home/alexey/turbo-geth/core/vm/evm.go:248 +0x494
github.com/ledgerwatch/turbo-geth/core.(*StateTransition).TransitionDb(0xc013b63ce0, 0x16f3720, 0xc010945ef0, 0xc0276924d8)
	/home/alexey/turbo-geth/core/state_transition.go:272 +0x400
github.com/ledgerwatch/turbo-geth/core.ApplyMessage(0xc002206580, 0x16f3720, 0xc010945ef0, 0xc0276924d8, 0xccc38c9abd03133, 0xbf0ec9fe, 0xc029bb6f20)
	/home/alexey/turbo-geth/core/state_transition.go:168 +0x57
github.com/ledgerwatch/turbo-geth/core.ApplyTransaction(0x21c88a0, 0x16d1f20, 0xc000488900, 0x0, 0xc0276924d8, 0xc00018ac00, 0x16e9760, 0x247a0c0, 0xc000c40d80, 0xc0016586c0, ...)
	/home/alexey/turbo-geth/core/state_processor.go:228 +0x31b
github.com/ledgerwatch/turbo-geth/core.ExecuteBlockEphemerally(0x21c88a0, 0xc000488cc8, 0x16d1f20, 0xc000488900, 0x16fa840, 0xc00019b0a0, 0xc0058d4f30, 0x7fc8503017e8, 0xc02dee9950, 0x16f0b40, ...)
	/home/alexey/turbo-geth/core/blockchain.go:2408 +0x4de
github.com/ledgerwatch/turbo-geth/eth/stagedsync.SpawnExecuteBlocksStage(0xc044e3cdb0, 0x16fcee0, 0xc00020d890, 0x7fc850268028, 0xc000488900, 0x0, 0xc00049eae0, 0x16e7320, 0xc0000101b0, 0xd3d300, ...)
	/home/alexey/turbo-geth/eth/stagedsync/stage_execute.go:161 +0xa6c
github.com/ledgerwatch/turbo-geth/eth/stagedsync.PrepareStagedSync.func7(0xc044e3cdb0, 0x16c0520, 0xc0138bc060, 0x3, 0x0)
	/home/alexey/turbo-geth/eth/stagedsync/stagedsync.go:77 +0x7f
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc0138bc060, 0xc001f03e00, 0x7fc850268068, 0xc00020d890, 0x3, 0x0, 0x0)
	/home/alexey/turbo-geth/eth/stagedsync/state.go:186 +0x217
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc0138bc060, 0x7fc8502680a8, 0xc00020d890, 0x7fc8502680a8, 0xc00020d890)
	/home/alexey/turbo-geth/eth/stagedsync/state.go:168 +0x304
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc00000c1e0, 0xc0006561e0, 0xdf982e5ba2c90c0b, 0x264cab7f101c7608, 0x367cdc7ce9b62814, 0x3e74426dfd373330, 0xc02680eb20, 0x16e7320, 0xc0000101b0, 0x0, ...)
	/home/alexey/turbo-geth/eth/downloader/downloader.go:580 +0xaf1
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc00000c1e0, 0xc000638370, 0x10, 0xdf982e5ba2c90c0b, 0x264cab7f101c7608, 0x367cdc7ce9b62814, 0x3e74426dfd373330, 0xc02680eb20, 0x3, 0x16e7320, ...)
	/home/alexey/turbo-geth/eth/downloader/downloader.go:455 +0x392
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc00000c1e0, 0xc000638370, 0x10, 0xdf982e5ba2c90c0b, 0x264cab7f101c7608, 0x367cdc7ce9b62814, 0x3e74426dfd373330, 0xc02680eb20, 0x3, 0x16e7320, ...)
	/home/alexey/turbo-geth/eth/downloader/downloader.go:352 +0xab
github.com/ledgerwatch/turbo-geth/eth.(*ProtocolManager).doSync(0xc00048a000, 0xc001956400, 0x16c0640, 0xc011033c20)
	/home/alexey/turbo-geth/eth/sync.go:315 +0xba
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync.func1(0xc00020dc20, 0xc001956400)
	/home/alexey/turbo-geth/eth/sync.go:287 +0x38
created by github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync
	/home/alexey/turbo-geth/eth/sync.go:287 +0x7a
````

**Comment by JekaMas** [comment]
@AlexeyAkhunov I can check do we have a memory leak or something if this issue is something that we want before the release.
