### ISSUE TITLE
Crash when cycling through the staged sync

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#846]
````
INFO [08-01|12:41:50.984] Sync stage 1/10. Download headers... DONE! 
INFO [08-01|12:41:50.984] Sync stage 2/10. Download block bodies... 
INFO [08-01|12:41:51.065] Imported new chain segment               blocks=1  txs=168   elapsed=41.892ms    number=10573936 hash="4fb767…6ba2cf"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfadf87]

goroutine 100 [running]:
github.com/ledgerwatch/turbo-geth/core/types.(*Block).NumberU64(...)
	github.com/ledgerwatch/turbo-geth/core/types/block.go:331
github.com/ledgerwatch/turbo-geth/eth.initPm.func3(0xc005ffd600, 0x1, 0x1, 0x274c401, 0xc009ba4ea0, 0x6)
	github.com/ledgerwatch/turbo-geth/eth/handler.go:203 +0x87
github.com/ledgerwatch/turbo-geth/eth/fetcher.(*BlockFetcher).insert(0xc0000a49a0, 0xc001c643b0, 0x10, 0xc009ba4cf0)
	github.com/ledgerwatch/turbo-geth/eth/fetcher/block_fetcher.go:711 +0x7ce
github.com/ledgerwatch/turbo-geth/eth/fetcher.(*BlockFetcher).loop(0xc0000a49a0)
	github.com/ledgerwatch/turbo-geth/eth/fetcher/block_fetcher.go:344 +0x47b
created by github.com/ledgerwatch/turbo-geth/eth/fetcher.(*BlockFetcher).Start
	github.com/ledgerwatch/turbo-geth/eth/fetcher/block_fetcher.go:202 +0x3f
````

**Comment by mandrigin** [comment]
@AlexeyAkhunov I don't see the code that calls NumberU64 in `inserter` func anymore. I guess you or someone else fixed it already.
