### ISSUE TITLE
Segfault likely due to full disk

### ISSUE THREAD

**Issue by pipermerriam** [ledgerwatch/turbo-geth#849]
#### System information

Geth version: 
```
Turbo-Geth
Version: 2020.07.0-alpha
Git Commit: 7eecbc5d2b2040c0542b0516b12322079e02e33c
Git Commit Date: 20200730
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.8
Operating System: linux
GOPATH=/home/piper/go
GOROOT=/usr/local/go
```

OS & Version: Linux
Commit hash : 7eecbc5d2b2040c0542b0516b12322079e02e33c

#### Expected behaviour

not to segfault

#### Actual behaviour

got a segfault (see stacktrace below) which was potentially caused by me running out of disk space.

Then when I try to restart the client:

```
Fatal: Error starting protocol stack: head block missing, hash af008f52810e073746a00b4a0a4cd7573b87c39162aadf618e48c52b76218d53
```

#### Steps to reproduce the behaviour

run out of disk space maybe?

#### Backtrace
```
ERROR[08-01|05:32:03.407] Invalid header encountered               number=10573612 hash="d65777…103722" err="unknown parent"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb848da]

goroutine 1136861 [running]:
github.com/ledgerwatch/turbo-geth/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth@/core/types/block.go:413 +0x4a
github.com/ledgerwatch/turbo-geth/core.(*BlockChain).Rollback(0xc00021e480, 0xc00769dd80, 0x1, 0x1)
        github.com/ledgerwatch/turbo-geth@/core/blockchain.go:870 +0x557
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).processHeaders.func1(0xc0004dbd70, 0xc00000c3c0)
        github.com/ledgerwatch/turbo-geth@/eth/downloader/downloader.go:1458 +0x1ee
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).processHeaders(0xc00000c3c0, 0xa1572c, 0x0, 0xa1572b, 0x1978860, 0xc020f3eb20)
        github.com/ledgerwatch/turbo-geth@/eth/downloader/downloader.go:1579 +0xde9
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer.func4(0xc00c98ff70, 0xc00c98ffb0)
        github.com/ledgerwatch/turbo-geth@/eth/downloader/downloader.go:564 +0x48
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync.func1(0xc00000c3c0, 0xc09bfcd8c0, 0xc01d813c50)
        github.com/ledgerwatch/turbo-geth@/eth/downloader/downloader.go:606 +0x63
created by github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync
        github.com/ledgerwatch/turbo-geth@/eth/downloader/downloader.go:606 +0xaf
```

**Comment by AlexeyAkhunov** [comment]
Thank you for reporting, I've got a fix for you coming soon. It should work with the database you've got

**Comment by pipermerriam** [comment]
I unfortunately rage-deleted the database and started re-syncing (realizing just afterwards that I was probably destroying valuable evidence....)

**Comment by AlexeyAkhunov** [comment]
````
NFO [08-01|05:31:50.214] Staged sync finished
INFO [08-01|05:31:50.214] Sync stage 1/10. Download headers...
INFO [08-01|05:31:50.667] Imported new block headers               count=1    elapsed=14.823ms    number=10573609 hash="b489be…6f20ba"
INFO [08-01|05:31:50.869] Sync stage 1/10. Download headers... DONE!
INFO [08-01|05:31:50.870] Sync stage 2/10. Download block bodies...
INFO [08-01|05:31:52.338] Imported new chain segment               blocks=11   txs=1916   elapsed=5.300ms     number=10569540 hash="4a2fd5…b4ac72" age=15h2m31s
WARN [08-01|05:31:52.862] Synchronisation failed, dropping peer    peer=3a87a19aaa210694 err="retrieved hash chain is invalid: commit inserting bodies: db.MultiPut failed: mdb_txn_commit: input/output error"
INFO [08-01|05:31:54.287] Staged sync finished
INFO [08-01|05:31:54.287] Sync stage 1/10. Download headers...
INFO [08-01|05:31:54.596] Imported new block headers               count=1    elapsed=47.834ms    number=10573610 hash="285b74…6159da"
INFO [08-01|05:31:54.677] Sync stage 1/10. Download headers... DONE!
INFO [08-01|05:31:54.677] Sync stage 2/10. Download block bodies...
INFO [08-01|05:31:55.296] Imported new chain segment               blocks=4    txs=884    elapsed=9.991ms     number=10569533 hash="af008f…218d53" age=15h3m46s
WARN [08-01|05:31:55.806] Synchronisation failed, dropping peer    peer=c5d772034e960c66 err="retrieved hash chain is invalid: commit inserting bodies: db.MultiPut failed: mdb_txn_commit: input/output error"
INFO [08-01|05:32:02.678] Staged sync finished
INFO [08-01|05:32:02.678] Sync stage 1/10. Download headers...
INFO [08-01|05:32:03.202] Imported new block headers               count=1    elapsed=43.593ms    number=10573611 hash="2963c1…236e0d"
````

**Comment by AlexeyAkhunov** [comment]
> I unfortunately rage-deleted the database and started re-syncing (realizing just afterwards that I was probably destroying valuable evidence....)
Yeah, we could have easily recovered your sync, but it should be recoverable from such situation soon (I had a similar problem)

**Comment by AlexeyAkhunov** [comment]
Fixed
