### ISSUE TITLE
stage3: morestack on g0, SIGTRAP 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#892]
```
turbo-geth_1  | INFO [08-08|21:54:24.192] Sync stage 2/10. Download block bodies... 
turbo-geth_1  | INFO [08-08|21:54:24.196] Sync stage 2/10. Download block bodies... DONE! 
turbo-geth_1  | INFO [08-08|21:54:24.196] Sync stage 3/10. Recover senders from tx signatures... 
turbo-geth_1  | INFO [08-08|21:54:24.196] Senders recovery                         from=0 to=10621713
turbo-geth_1  | INFO [08-08|22:13:57.713] Sync (Senders): Reading canonical hashes complete hashes=10621713
turbo-geth_1  | INFO [08-08|22:13:57.713] Sync (Senders): Started recoverer goroutines numOfGoroutines=6
turbo-geth_1  | fatal: morestack on g0
turbo-geth_1  | fatal: morestack on g0
turbo-geth_1  | SIGTRAP: trace trap
turbo-geth_1  | PC=0x485cc2 m=3 sigcode=128
turbo-geth_1  | 
turbo-geth_1  | goroutine 0 [idle]:
turbo-geth_1  | runtime.abort()
turbo-geth_1  |     runtime/asm_amd64.s:859 +0x2
turbo-geth_1  | runtime.morestack()
turbo-geth_1  |     runtime/asm_amd64.s:416 +0x25
turbo-geth_1  | 
turbo-geth_1  | goroutine 29881 [syscall]:
turbo-geth_1  | runtime.cgocall(0x1123770, 0xc0006e9740, 0x1)
turbo-geth_1  |     runtime/cgocall.go:133 +0x5b fp=0xc0006e9710 sp=0xc0006e96d8 pc=0x42158b
turbo-geth_1  | github.com/ledgerwatch/turbo-geth/crypto/secp256k1._Cfunc_secp256k1_context_create_sign_verify(0x0)
turbo-geth_1  |     _cgo_gotypes.go:156 +0x4a fp=0xc0006e9740 sp=0xc0006e9710 pc=0x60aaba
turbo-geth_1  | github.com/ledgerwatch/turbo-geth/crypto/secp256k1.initContext(0x0)
turbo-geth_1  |     github.com/ledgerwatch/turbo-geth/crypto/secp256k1/secp256.go:56 +0x22 fp=0xc0006e9760 sp=0xc0006e9740 pc=0x60d902
```

#### System information

Linux imub100odbax001 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Docker version 19.03.12, build 48a66213fe
CPUinfo: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (x6)

docker-compose (FROM golang:1.14-alpine as builder)

**Comment by AskAlexSharov** [comment]
Found few related things: 
- same issue related to go-ethereum crypto lib: https://gitter.im/heroiclabs/nakama?at=5da552cc89acff6ff5fa40a0
- and here is some reproducable example: https://juejin.im/post/6847902223255470087
- and here is open golang issue: https://github.com/golang/go/issues/39457
