### ISSUE TITLE
Implement net_version

### ISSUE THREAD

**Issue by akme** [ledgerwatch/turbo-geth#923]
Hi there,
Would be nice to have net_version method working, trying to use turbo-geth with The Graph Indexers gives this:
```
Aug 15 09:41:34.723 WARN Trying again after net_version RPC call failed (attempt #19) with result Err(Rpc(Error { code: MethodNotFound, message: "the method net_version does not exist/is not available", data: None }))
```

**Comment by akme** [comment]
```
$ ./build/bin/rpcdaemon --chaindata ~/.local/share/turbogeth/tg/chaindata/ --http.api=eth,debug,net
INFO [08-17|16:24:40.855] HTTP endpoint opened                     url=http://localhost:8545
ERROR[08-17|16:24:50.639] RPC method net_version crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 28 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc0000d1a53, 0xb, 0xc0002f4cf8)
	github.com/ledgerwatch/turbo-geth@/rpc/service.go:200 +0xb5
panic(0xf59880, 0x19b9470)
	runtime/panic.go:679 +0x1b2
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*NetAPIImpl).Version(0xc0000c5e40, 0x128af40, 0xc0001c8a40, 0x0)
	github.com/ledgerwatch/turbo-geth@/cmd/rpcdaemon/commands/net_version.go:8 +0x29
reflect.Value.call(0xc000032d80, 0xc0000d48e8, 0x13, 0x10c26f8, 0x4, 0xc000167740, 0x2, 0x2, 0xc0002f4b70, 0x465d5c, ...)
	reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc000032d80, 0xc0000d48e8, 0x13, 0xc000167740, 0x2, 0x2, 0x0, 0x0, 0x0)
	reflect/value.go:321 +0xb4
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000032de0, 0x128af40, 0xc0001c8a40, 0xc0000d1a53, 0xb, 0x1af7e80, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth@/rpc/service.go:206 +0x2b9
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc00011c5a0, 0x128af40, 0xc0001c8a40, 0xc0000f2d90, 0xc000032de0, 0x1af7e80, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:389 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc00011c5a0, 0xc0001673b0, 0xc0000f2d90, 0x42dbee)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:337 +0x298
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc00011c5a0, 0xc0001673b0, 0xc0000f2d90, 0x1276f01)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:298 +0x1f3
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc0001673b0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc00011c5a0, 0xc0000e1fe0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:226 +0x119
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:222 +0x66

WARN [08-17|16:24:50.639] Served net_version                       conn=172.28.0.10:38020 reqid=26401 t="131.303µs" err="method handler crashed"
```
