### ISSUE TITLE
panic: lstat .//OE: host is down

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#987]
I just pulled and compiled the master branch, running on ubuntu 18.04
After a while i'm seeing this on repeat.

```
Started ETH archive node (turbogeth).
INFO [08-28|01:49:46.965] Starting Turbo-Geth on Ethereum mainnet...
INFO [08-28|01:49:46.965] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-28|01:49:46.967] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-28|01:49:46.967] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-28|01:49:46.967] Set LMDB map size                        lmdb.mapSize="2.0 TB"
INFO [08-28|01:49:46.967] Set global gas cap                       cap=25000000
INFO [08-28|01:49:46.967] Allocated trie memory caches             clean=1.60GiB dirty=0.00B
INFO [08-28|01:49:46.967] Opening Database (LMDB)
INFO [08-28|01:49:46.970] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v1: <nil>, Engine: ethash}"
INFO [08-28|01:49:46.970] Disk storage enabled for ethash DAGs     dir=/home/<user>/.local/share/tg-ethash count=2
INFO [08-28|01:49:46.970] Initialising Ethereum protocol           versions="[65 64]" network=1
panic: lstat .//OE: host is down
goroutine 1 [running]:
github.com/ledgerwatch/turbo-geth/core.NewBlockValidator(0x22c2dc0, 0xc000279200, 0x17550a0, 0xc000252300, 0x0)
        github.com/ledgerwatch/turbo-geth/core/block_validator.go:57 +0x726
github.com/ledgerwatch/turbo-geth/core.NewBlockChain(0x1757d20, 0xc0003e56e0, 0xc00026c770, 0x22c2dc0, 0x17550a0, 0xc000252300, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/blockchain.go:239 +0x32b
github.com/ledgerwatch/turbo-geth/eth.New(0xc00056ac40, 0xc000171200, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/backend.go:197 +0xf91
github.com/ledgerwatch/turbo-geth/cmd/utils.RegisterEthService(0xc00056ac40, 0xc000171200, 0x0)
        github.com/ledgerwatch/turbo-geth/cmd/utils/flags.go:1686 +0x39
main.makeFullNode(0xc0001722c0, 0x147e701, 0x0)
        github.com/ledgerwatch/turbo-geth/cmd/geth/config.go:139 +0xcf
main.geth(0xc0001722c0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/cmd/geth/main.go:349 +0xf7
github.com/urfave/cli.HandleAction(0x125c7a0, 0x155cd18, 0xc0001722c0, 0xc0001722c0, 0x0)
        github.com/urfave/cli@v1.22.1/app.go:523 +0x11a
github.com/urfave/cli.(*App).Run(0xc00021dc00, 0xc0001181b0, 0x1, 0x1, 0x0, 0x0)
        github.com/urfave/cli@v1.22.1/app.go:285 +0x630
main.main()
        github.com/ledgerwatch/turbo-geth/cmd/geth/main.go:266 +0x55
turbogeth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
turbogeth.service: Failed with result 'exit-code'.
turbogeth.service: Service hold-off time over, scheduling restart.
turbogeth.service: Scheduled restart job, restart counter is at 1115.
Stopped ETH archive node (turbogeth).
```

**Comment by koen84** [comment]
Restarting the service immedately brings me into the same loop.

**Comment by AskAlexSharov** [comment]
Hi. 
1. `/home/<user>` -  have you set correct dir?
2. Please show with which flags you run TG?

**Comment by koen84** [comment]
1. Yes, i "blanked out" the actual user.
2. No flags, just `./tg`

This install used to work.  I'm fairly certain that when i had just checkout latest master and built it, it ran for a while.  (Noticed in the logs the subdir for ETL files, among other things.)

**Comment by AskAlexSharov** [comment]
Somehow TG can't read current dir... error coming from `ioutil.ReadDir("./")`
Can you try to run branch `cwd_err` - added there a bit logs about cwd

**Comment by AskAlexSharov** [comment]
hmm... but why do we need to read cwd... 
go-ethereum doesn't https://github.com/ethereum/go-ethereum/blob/master/core/block_validator.go#L40
@AlexeyAkhunov , FYI, i removing all FS interactions from `core/block_validator.go:NewBlockValidator

**Comment by koen84** [comment]
Weird, in $HOME i have with `ls -l` this entry
`d?????????  ? ?     ?        ?            ? OE`

**Comment by koen84** [comment]
And if i try to `ls OE` i get 
`ls: cannot access '/home/graph/OE': Host is down`

File permissions of $HOME and its subdirectories seem good.

**Comment by AskAlexSharov** [comment]
It looks as old debug code for me, probably need just delete it and don't read your homedir

**Comment by koen84** [comment]
Okay, the weird directory was a cifs mount point that dropped.  After `umount` and `mount -a` the connection restored.  Then turbogeth is running fine again.  Not sure why turbogeth crashed over it, it's (currently) not storing anything there.

**Comment by AskAlexSharov** [comment]
TG is a curious guy

**Comment by AlexeyAkhunov** [comment]
It should be fixed by https://github.com/ledgerwatch/turbo-geth/pull/992, thank you @AskAlexSharov and @koen84
